"""Tennis training catalog for Sportze.AI.

This module contains tennis workouts and exercises codified from the Sportze.AI
training catalog. It is import-safe and ready for catalog manager integration.
"""

from __future__ import annotations

from typing import Any, Dict, List

SPORT = "tennis"
SPORT_NAME = "Tennis"


def exercise(name: str, prescription: str, notes: str | None = None) -> Dict[str, Any]:
    item: Dict[str, Any] = {"name": name, "prescription": prescription}
    if notes:
        item["notes"] = notes
    return item


def session(
    name: str,
    category: str,
    training_type: str,
    participants: str,
    exercises: List[Dict[str, Any]],
    level: str | None = None,
    focus: str | None = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "sport": SPORT,
        "name": name,
        "category": category,
        "training_type": training_type,
        "participants": participants,
        "exercises": exercises,
    }
    if level:
        data["level"] = level
    if focus:
        data["focus"] = focus
    return data


TENNIS_SESSIONS: List[Dict[str, Any]] = [{'sport': 'tennis',
  'name': 'Learn How To Play - Training Alone',
  'category': 'Learn How To Play',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Wall Forehands',
                 'prescription': '200 forehands',
                 'notes': 'Stand 4 meters from a wall; do not allow a second bounce.'},
                {'name': 'Wall Backhands',
                 'prescription': '200 backhands',
                 'notes': 'Use normal grip and maintain shoulder-height contact.'},
                {'name': 'Alternating Wall Rally',
                 'prescription': '150 total shots',
                 'notes': 'Alternate one forehand and one backhand.'},
                {'name': 'Forehand Shadow Swings',
                 'prescription': '100 reps',
                 'notes': 'Finish over opposite shoulder.'},
                {'name': 'Backhand Shadow Swings',
                 'prescription': '100 reps',
                 'notes': 'Return to ready position after every swing.'},
                {'name': 'Deuce Box Serves',
                 'prescription': '80 serves',
                 'notes': 'Focus only on landing inside the deuce service box.'},
                {'name': 'Ad Box Serves',
                 'prescription': '80 serves',
                 'notes': 'Focus only on landing inside the ad service box.'},
                {'name': 'Split-Step Corner Movement',
                 'prescription': '4 minutes',
                 'notes': 'Split-step then move to each court corner.'},
                {'name': 'Racket Balance Walk',
                 'prescription': '10 full court laps',
                 'notes': 'Balance the ball on the racket while walking.'},
                {'name': 'Alternating Racket Bounces',
                 'prescription': '300 touches',
                 'notes': 'Alternate forehand and backhand faces.'},
                {'name': 'Overhead Smash Shadow',
                 'prescription': '60 reps',
                 'notes': 'Recover to baseline after each swing.'},
                {'name': 'Singles Court Footwork',
                 'prescription': '10 minutes',
                 'notes': 'Continuous footwork around the singles court without hitting a ball.'}],
  'level': 'learn',
  'focus': 'basic tennis strokes, serves, racket control, and footwork'},
 {'sport': 'tennis',
  'name': 'Learn How To Play - Hitting Partner',
  'category': 'Learn How To Play',
  'training_type': 'technical',
  'participants': 'with_partner',
  'exercises': [{'name': 'Forehand Crosscourt Rally', 'prescription': '100 consecutive shots'},
                {'name': 'Backhand Crosscourt Rally', 'prescription': '100 consecutive shots'},
                {'name': 'Alternating FH/BH Rally', 'prescription': '120 consecutive rallies'},
                {'name': 'Crosscourt Feed Returns', 'prescription': '80 balls each before switching'},
                {'name': 'Singles Court Control Rally',
                 'prescription': '10 minutes',
                 'notes': 'Hit only inside the singles court without keeping score.'},
                {'name': 'Serve Basket Catch', 'prescription': '80 serves', 'notes': 'Partner catches every serve.'},
                {'name': 'Serve and Crosscourt Return', 'prescription': '60 points each before switching'},
                {'name': 'Mini-Tennis', 'prescription': '12 minutes', 'notes': 'Play inside service boxes.'},
                {'name': 'Half-Speed Rally', 'prescription': '200 total shots', 'notes': 'Emphasize consistency.'},
                {'name': 'Second-Serve Tiebreak',
                 'prescription': '1 tiebreak to 7',
                 'notes': 'Use only second serves.'}],
  'level': 'learn',
  'focus': 'basic partner rallying, serving, receiving, and mini-tennis'},
 {'sport': 'tennis',
  'name': 'Beginner - Training Alone',
  'category': 'Beginner',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Wall Forehands Above Service Line', 'prescription': '250 forehands'},
                {'name': 'Wall Backhands', 'prescription': '250 backhands'},
                {'name': 'Alternating Wall Hits', 'prescription': '200 wall hits'},
                {'name': 'Alternating Flat Serves', 'prescription': '100 serves'},
                {'name': 'Deuce Wide Slice Serves', 'prescription': '60 serves'},
                {'name': 'Ad Wide Slice Serves', 'prescription': '60 serves'},
                {'name': 'Split-Step Corner Sprints', 'prescription': '6 minutes'},
                {'name': 'Approach Shot to Volley Shadow', 'prescription': '80 reps'},
                {'name': 'Doubles Alley Recovery Shadow', 'prescription': '80 reps'},
                {'name': 'Forehand Target Hitting',
                 'prescription': '80 successful targets',
                 'notes': 'Four cone targets near each opposite baseline corner.'},
                {'name': 'Backhand Target Hitting',
                 'prescription': '80 successful targets',
                 'notes': 'Same target drill using backhands.'},
                {'name': 'Random Movement Shadow Tennis', 'prescription': '5 minutes'}],
  'level': 'beginner',
  'focus': 'wall strokes, serves, recovery, approach movement, and target control'},
 {'sport': 'tennis',
  'name': 'Beginner - Hitting Partner',
  'category': 'Beginner',
  'training_type': 'technical',
  'participants': 'with_partner',
  'exercises': [{'name': 'Forehand Crosscourt Rally', 'prescription': '150 rallies'},
                {'name': 'Backhand Crosscourt Rally', 'prescription': '150 rallies'},
                {'name': 'Crosscourt Forehand to Down-Line Backhand', 'prescription': '100 shots'},
                {'name': 'Controlled Topspin Feed Drill', 'prescription': '80 balls each before switching'},
                {'name': 'Mini-Tennis Below Shoulder Height', 'prescription': '15 minutes'},
                {'name': 'Serve Return Third Shot Stop', 'prescription': '80 points'},
                {'name': 'Approach Shot and Volley', 'prescription': '60 reps each'},
                {'name': 'Six-Shot Minimum Set',
                 'prescription': '1 set',
                 'notes': 'Rally must include at least six shots before a winner.'},
                {'name': 'Crosscourt-Only Game', 'prescription': '1 game'},
                {'name': 'Tiebreaks', 'prescription': '2 tiebreaks to 7'}],
  'level': 'beginner',
  'focus': 'rally consistency, third-shot patterns, approach play, and competitive basics'},
 {'sport': 'tennis',
  'name': 'Baseline Aggressor - Training Alone',
  'category': 'Baseline Aggressor',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '150 maximum-controlled wall forehands'},
                {'name': 'Exercise 2', 'prescription': '120 inside-out forehand shadow swings'},
                {'name': 'Exercise 3', 'prescription': '100 step-around forehand attack shadows'},
                {'name': 'Exercise 4', 'prescription': '80 serve-wide recover first-forehand shadows'},
                {'name': 'Exercise 5', 'prescription': '120 deep crosscourt forehand targets'},
                {'name': 'Exercise 6', 'prescription': '120 deep down-the-line forehand targets'},
                {'name': 'Exercise 7', 'prescription': '80 aggressive forehand plus recovery reps'},
                {'name': 'Exercise 8',
                 'prescription': '8 minutes suicide runs to four singles corners with shadow swings'},
                {'name': 'Exercise 9', 'prescription': '60 running forehand shadows outside doubles alley'},
                {'name': 'Exercise 10', 'prescription': '50 explosive forehand winner shadows'}],
  'focus': 'baseline aggressor'},
 {'sport': 'tennis',
  'name': 'Baseline Aggressor - Hitting Partner',
  'category': 'Baseline Aggressor',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '150 forehand crosscourt rally shots'},
                {'name': 'Exercise 2', 'prescription': '120 partner-fed forehand attacks'},
                {'name': 'Exercise 3', 'prescription': '80 serve plus first aggressive ball repetitions'},
                {'name': 'Exercise 4', 'prescription': '100 inside-out forehand balls'},
                {'name': 'Exercise 5', 'prescription': '80 alternating crosscourt/down-line forehand winners'},
                {'name': 'Exercise 6', 'prescription': '70 random short-ball attacks'},
                {'name': 'Exercise 7', 'prescription': 'Points starting with forehand approach only'},
                {'name': 'Exercise 8', 'prescription': '1 set where every winner must be forehand'},
                {'name': 'Exercise 9', 'prescription': '120 aggressive forehands while partner blocks'},
                {'name': 'Exercise 10', 'prescription': '3 games emphasizing first-strike tennis'}],
  'focus': 'baseline aggressor'},
 {'sport': 'tennis',
  'name': 'Counterpuncher - Training Alone',
  'category': 'Counterpuncher',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '300 alternating wall rally shots without increasing pace'},
                {'name': 'Exercise 2', 'prescription': '100 defensive recoveries alley-to-alley'},
                {'name': 'Exercise 3', 'prescription': '8 minutes continuous crossover baseline footwork'},
                {'name': 'Exercise 4', 'prescription': '80 backward-moving defensive forehand shadows'},
                {'name': 'Exercise 5', 'prescription': '80 backward-moving defensive backhand shadows'},
                {'name': 'Exercise 6', 'prescription': '120 defensive slice backhands plus recovery'},
                {'name': 'Exercise 7', 'prescription': '80 high looping topspin forehand shadows'},
                {'name': 'Exercise 8', 'prescription': '50 sprint-recovery-sprint baseline sequences'},
                {'name': 'Exercise 9', 'prescription': '60 passing shot shadows each side'},
                {'name': 'Exercise 10', 'prescription': '10 minutes nonstop defensive footwork'}],
  'focus': 'counterpuncher'},
 {'sport': 'tennis',
  'name': 'Counterpuncher - Hitting Partner',
  'category': 'Counterpuncher',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '200-shot rally without winners'},
                {'name': 'Exercise 2', 'prescription': '100 balls returning partner attacks deep'},
                {'name': 'Exercise 3', 'prescription': '120 alternating high topspin and deep slice rallies'},
                {'name': 'Exercise 4', 'prescription': 'Passing shots only against net approaches'},
                {'name': 'Exercise 5', 'prescription': '100 random-corner recovery shots'},
                {'name': 'Exercise 6', 'prescription': '1 set where every rally exceeds 8 shots'},
                {'name': 'Exercise 7', 'prescription': '80 alternating defensive slice/topspin rallies'},
                {'name': 'Exercise 8', 'prescription': '1 game recovering to middle after every ball'},
                {'name': 'Exercise 9', 'prescription': '1 full basket of deep returns against aggressive serves'},
                {'name': 'Exercise 10', 'prescription': 'Tiebreak focused only on consistency'}],
  'focus': 'counterpuncher'},
 {'sport': 'tennis',
  'name': 'All-Court Player - Training Alone',
  'category': 'All-Court Player',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1',
                 'prescription': '50 forehands, 50 backhands, 50 slices, 50 volleys against wall'},
                {'name': 'Exercise 2', 'prescription': '80 baseline-approach-two-volley shadow sequences'},
                {'name': 'Exercise 3', 'prescription': '60 serve-wide first forehand approach overhead sequences'},
                {'name': 'Exercise 4', 'prescription': '100 alternating FH/BH approach shots'},
                {'name': 'Exercise 5', 'prescription': '80 forehand volleys from 2m against wall'},
                {'name': 'Exercise 6', 'prescription': '80 backhand volleys from 2m against wall'},
                {'name': 'Exercise 7', 'prescription': '100 baseline-to-service-line transitions'},
                {'name': 'Exercise 8', 'prescription': '150 alternating topspin forehands and slice backhands'},
                {'name': 'Exercise 9', 'prescription': '40 baseline-net shadow volley recoveries'},
                {'name': 'Exercise 10', 'prescription': '5 minutes random shadow tennis covering every stroke'}],
  'focus': 'all-court player'},
 {'sport': 'tennis',
  'name': 'All-Court Player - Hitting Partner',
  'category': 'All-Court Player',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '80 crosscourt rally to approach and finish points'},
                {'name': 'Exercise 2', 'prescription': '100 alternating short/deep ball returns'},
                {'name': 'Exercise 3', 'prescription': '60 baseline rally plus serve-and-volley repetitions'},
                {'name': 'Exercise 4', 'prescription': '80 approach-shot and volley repetitions'},
                {'name': 'Exercise 5', 'prescription': '1 set with at least one volley every point'},
                {'name': 'Exercise 6', 'prescription': '80 alternating topspin and slice rallies'},
                {'name': 'Exercise 7', 'prescription': '1 transition-tennis only game'},
                {'name': 'Exercise 8', 'prescription': '60 lob recovery overheads'},
                {'name': 'Exercise 9', 'prescription': '80 alternating baseline and net winners'},
                {'name': 'Exercise 10', 'prescription': '2 competitive all-court tiebreaks'}],
  'focus': 'all-court player'},
 {'sport': 'tennis',
  'name': 'Serve & Return Specialist - Training Alone',
  'category': 'Serve & Return Specialist',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '100 flat first serves down the T'},
                {'name': 'Exercise 2', 'prescription': '100 wide slice serves from deuce court'},
                {'name': 'Exercise 3', 'prescription': '100 kick serves to backhand side'},
                {'name': 'Exercise 4', 'prescription': '150 alternating flat/slice/kick serves'},
                {'name': 'Exercise 5', 'prescription': 'Hit six cone targets 15 times each'},
                {'name': 'Exercise 6', 'prescription': '120 split-step return preparation shadows'},
                {'name': 'Exercise 7', 'prescription': '80 forehand return shadows'},
                {'name': 'Exercise 8', 'prescription': '80 backhand return shadows'},
                {'name': 'Exercise 9', 'prescription': '80 serve recover first attacking shot shadows'},
                {'name': 'Exercise 10', 'prescription': '1 full basket with no two consecutive faults'}],
  'focus': 'serve & return specialist'},
 {'sport': 'tennis',
  'name': 'Serve & Return Specialist - Hitting Partner',
  'category': 'Serve & Return Specialist',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '80 first serves with partner returning'},
                {'name': 'Exercise 2', 'prescription': '100 first-serve returns crosscourt'},
                {'name': 'Exercise 3', 'prescription': '100 second-serve aggressive returns'},
                {'name': 'Exercise 4', 'prescription': '60 wide serve plus attack repetitions'},
                {'name': 'Exercise 5', 'prescription': '80 random first/second serve returns'},
                {'name': 'Exercise 6', 'prescription': '60 body serves'},
                {'name': 'Exercise 7', 'prescription': '80 return plus first attacking shot repetitions'},
                {'name': 'Exercise 8', 'prescription': '1 set with only second serves'},
                {'name': 'Exercise 9', 'prescription': '6 alternating deuce/ad service games'},
                {'name': 'Exercise 10', 'prescription': '1 tiebreak above 70% first-serve target'}],
  'focus': 'serve & return specialist'},
 {'sport': 'tennis',
  'name': 'Net Play & Volley Specialist - Training Alone',
  'category': 'Net Play & Volley Specialist',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '150 forehand wall volleys from 2m'},
                {'name': 'Exercise 2', 'prescription': '150 backhand wall volleys'},
                {'name': 'Exercise 3', 'prescription': '80 self-fed overhead smashes'},
                {'name': 'Exercise 4', 'prescription': '100 service-line split-step volley shadows'},
                {'name': 'Exercise 5', 'prescription': '120 alternating FH/BH volleys'},
                {'name': 'Exercise 6', 'prescription': '40 baseline-net two-volley recoveries'},
                {'name': 'Exercise 7', 'prescription': '80 low-volley pickups against wall'},
                {'name': 'Exercise 8', 'prescription': '80 half-volley shadows'},
                {'name': 'Exercise 9', 'prescription': '5 minutes close-distance reaction volleys'},
                {'name': 'Exercise 10', 'prescription': '50 explosive overhead smashes'}],
  'focus': 'net play & volley specialist'},
 {'sport': 'tennis',
  'name': 'Net Play & Volley Specialist - Hitting Partner',
  'category': 'Net Play & Volley Specialist',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '120 continuous fed volleys'},
                {'name': 'Exercise 2', 'prescription': '80 short-ball approach repetitions'},
                {'name': 'Exercise 3', 'prescription': '80 passing-shot volley points'},
                {'name': 'Exercise 4', 'prescription': '60 overheads after lobs'},
                {'name': 'Exercise 5', 'prescription': 'Volley-only points to 11'},
                {'name': 'Exercise 6', 'prescription': '120 alternating FH/BH volley rallies'},
                {'name': 'Exercise 7', 'prescription': '100 rapid reaction volleys'},
                {'name': 'Exercise 8', 'prescription': '1 serve-and-volley set'},
                {'name': 'Exercise 9', 'prescription': '1 approach-and-volley set'},
                {'name': 'Exercise 10', 'prescription': '10 minutes doubles-style net exchanges'}],
  'focus': 'net play & volley specialist'},
 {'sport': 'tennis',
  'name': 'Clay Court Endurance - Training Alone',
  'category': 'Clay Court Endurance',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '80 forehand slide shadows'},
                {'name': 'Exercise 2', 'prescription': '80 backhand slide shadows'},
                {'name': 'Exercise 3', 'prescription': '10 minutes continuous baseline movement'},
                {'name': 'Exercise 4', 'prescription': '200 heavy topspin wall forehands'},
                {'name': 'Exercise 5', 'prescription': '200 topspin wall backhands'},
                {'name': 'Exercise 6', 'prescription': '120 defensive recovery shadows'},
                {'name': 'Exercise 7', 'prescription': '50 corner-to-corner sprints with controlled deceleration'},
                {'name': 'Exercise 8', 'prescription': '80 moonball shadow swings'},
                {'name': 'Exercise 9', 'prescription': '8 minutes alternating offensive/defensive footwork'},
                {'name': 'Exercise 10', 'prescription': '10 minutes full singles-court continuous movement'}],
  'focus': 'clay court endurance'},
 {'sport': 'tennis',
  'name': 'Clay Court Endurance - Hitting Partner',
  'category': 'Clay Court Endurance',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '300-shot rally'},
                {'name': 'Exercise 2', 'prescription': '15 minutes topspin-only rallies'},
                {'name': 'Exercise 3', 'prescription': '120 deep-ball recovery shots'},
                {'name': 'Exercise 4', 'prescription': 'Alternate offense and defense every five shots'},
                {'name': 'Exercise 5', 'prescription': 'Points where winners only after 8 shots'},
                {'name': 'Exercise 6', 'prescription': '80 defensive lobs'},
                {'name': 'Exercise 7', 'prescription': '1 height-and-topspin game'},
                {'name': 'Exercise 8', 'prescription': '1 depth-only game'},
                {'name': 'Exercise 9', 'prescription': '3 extended tiebreaks'},
                {'name': 'Exercise 10', 'prescription': '1 endurance set to six games'}],
  'focus': 'clay court endurance'},
 {'sport': 'tennis',
  'name': 'Hard Court Power - Training Alone',
  'category': 'Hard Court Power',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '150 flat forehands against wall'},
                {'name': 'Exercise 2', 'prescription': '150 flat backhands against wall'},
                {'name': 'Exercise 3', 'prescription': '100 maximum-pace flat serves'},
                {'name': 'Exercise 4', 'prescription': '100 explosive first-step shadows'},
                {'name': 'Exercise 5', 'prescription': '40 baseline-to-service-line sprints and back'},
                {'name': 'Exercise 6', 'prescription': '80 inside-out forehand winner shadows'},
                {'name': 'Exercise 7', 'prescription': '80 return-and-attack shadows'},
                {'name': 'Exercise 8', 'prescription': '100 successful maximum-pace deep targets'},
                {'name': 'Exercise 9', 'prescription': '5 minutes explosive split-step drills'},
                {'name': 'Exercise 10', 'prescription': '50 maximum-speed shadow forehands'}],
  'focus': 'hard court power'},
 {'sport': 'tennis',
  'name': 'Hard Court Power - Hitting Partner',
  'category': 'Hard Court Power',
  'training_type': 'game_based',
  'participants': 'with_partner',
  'exercises': [{'name': 'Exercise 1', 'prescription': '120 aggressive baseline rally shots'},
                {'name': 'Exercise 2', 'prescription': '80 short-ball attacks'},
                {'name': 'Exercise 3', 'prescription': '80 serve plus first-ball winner points'},
                {'name': 'Exercise 4', 'prescription': '120 fast-paced fed attacks'},
                {'name': 'Exercise 5', 'prescription': 'Alternating crosscourt and down-the-line winners'},
                {'name': 'Exercise 6', 'prescription': 'Points ending within four shots'},
                {'name': 'Exercise 7', 'prescription': '80 aggressive returns'},
                {'name': 'Exercise 8', 'prescription': '1 set emphasizing pace over spin'},
                {'name': 'Exercise 9', 'prescription': '100 continuous attacks while partner blocks'},
                {'name': 'Exercise 10', 'prescription': 'Fast-paced tiebreak to 10'}],
  'focus': 'hard court power'},
 {'sport': 'tennis',
  'name': 'Doubles Positioning & Movement - Just Me',
  'category': 'Doubles Positioning & Movement',
  'training_type': 'doubles',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '120 shadow doubles rotation cycles'},
                {'name': 'Exercise 2', 'prescription': '50 baseline-to-net diagonal recoveries'},
                {'name': 'Exercise 3', 'prescription': '100 poaching footwork reps without ball'},
                {'name': 'Exercise 4', 'prescription': '80 serve move forward cover-middle reps'},
                {'name': 'Exercise 5', 'prescription': '80 switching-sides volley shadows'},
                {'name': 'Exercise 6', 'prescription': '60 Australian formation shadows'},
                {'name': 'Exercise 7', 'prescription': '60 I-formation shadows'},
                {'name': 'Exercise 8', 'prescription': '10 minutes random doubles footwork'}],
  'focus': 'doubles positioning & movement'},
 {'sport': 'tennis',
  'name': 'Doubles Positioning & Movement - My Partner and I',
  'category': 'Doubles Positioning & Movement',
  'training_type': 'doubles',
  'participants': 'pair',
  'exercises': [{'name': 'Exercise 1', 'prescription': '100 alternating volleys with switches'},
                {'name': 'Exercise 2', 'prescription': '60 poaches after every third volley'},
                {'name': 'Exercise 3', 'prescription': '80 serve-and-close-net points'},
                {'name': 'Exercise 4', 'prescription': '1 set communication calls before every point'},
                {'name': 'Exercise 5', 'prescription': 'Alternate baseline/net duties every game'},
                {'name': 'Exercise 6', 'prescription': '80 middle-ball coverage reps'},
                {'name': 'Exercise 7', 'prescription': '10 minutes half-court doubles rallies'},
                {'name': 'Exercise 8', 'prescription': '1 full doubles set'}],
  'focus': 'doubles positioning & movement'},
 {'sport': 'tennis',
  'name': 'Doubles Positioning & Movement - Three Players',
  'category': 'Doubles Positioning & Movement',
  'training_type': 'doubles',
  'participants': 'three_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': 'One fixed opponent while pair rotates every point'},
                {'name': 'Exercise 2', 'prescription': 'Rotate server after every game'},
                {'name': 'Exercise 3', 'prescription': '80 two-versus-one net coverage points'},
                {'name': 'Exercise 4', 'prescription': 'Alternate poaching every five rallies'},
                {'name': 'Exercise 5', 'prescription': '15 minutes continuous rotation drills'},
                {'name': 'Exercise 6', 'prescription': '120 fed balls for pair movement'},
                {'name': 'Exercise 7', 'prescription': 'Switch formations every game'},
                {'name': 'Exercise 8', 'prescription': 'Rotating doubles games'}],
  'focus': 'doubles positioning & movement'},
 {'sport': 'tennis',
  'name': 'Doubles Positioning & Movement - Four Players',
  'category': 'Doubles Positioning & Movement',
  'training_type': 'doubles',
  'participants': 'four_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': '3 games standard doubles formations'},
                {'name': 'Exercise 2', 'prescription': '2 games Australian formation'},
                {'name': 'Exercise 3', 'prescription': '2 games I-formation'},
                {'name': 'Exercise 4', 'prescription': 'Alternate serve-and-volley formations every game'},
                {'name': 'Exercise 5', 'prescription': '80 poaching drill points'},
                {'name': 'Exercise 6', 'prescription': '100 middle-ball communication rallies'},
                {'name': 'Exercise 7', 'prescription': '10 minutes crosscourt-only doubles'},
                {'name': 'Exercise 8', 'prescription': 'Best-of-three doubles match'}],
  'focus': 'doubles positioning & movement'},
 {'sport': 'tennis',
  'name': 'Doubles Serve & Return Patterns - Just Me',
  'category': 'Doubles Serve & Return Patterns',
  'training_type': 'doubles',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '100 serve then immediate net approach shadows'},
                {'name': 'Exercise 2', 'prescription': '80 return then cover crosscourt shadows'},
                {'name': 'Exercise 3', 'prescription': '80 partner-cover movements after serve'},
                {'name': 'Exercise 4', 'prescription': '100 deuce/ad serving motions'},
                {'name': 'Exercise 5', 'prescription': '60 poach after imaginary return shadows'},
                {'name': 'Exercise 6', 'prescription': '5 minutes net split-step timing'},
                {'name': 'Exercise 7', 'prescription': '60 return-and-lob shadows'},
                {'name': 'Exercise 8', 'prescription': 'Random doubles movement finish'}],
  'focus': 'doubles serve & return patterns'},
 {'sport': 'tennis',
  'name': 'Doubles Serve & Return Patterns - My Partner and I',
  'category': 'Doubles Serve & Return Patterns',
  'training_type': 'doubles',
  'participants': 'pair',
  'exercises': [{'name': 'Exercise 1', 'prescription': '80 serve-and-volley-together points'},
                {'name': 'Exercise 2', 'prescription': '60 return plus poach reps'},
                {'name': 'Exercise 3', 'prescription': 'Alternate wide and body serves every point'},
                {'name': 'Exercise 4', 'prescription': '10 minutes serve-return-volley patterns'},
                {'name': 'Exercise 5', 'prescription': 'Communication before every serve'},
                {'name': 'Exercise 6', 'prescription': '80 returns down the middle'},
                {'name': 'Exercise 7', 'prescription': 'Alternate server every game with formations'},
                {'name': 'Exercise 8', 'prescription': '1 doubles tiebreak'}],
  'focus': 'doubles serve & return patterns'},
 {'sport': 'tennis',
  'name': 'Doubles Serve & Return Patterns - Three Players',
  'category': 'Doubles Serve & Return Patterns',
  'training_type': 'doubles',
  'participants': 'three_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': 'One player serves while pair practices returns'},
                {'name': 'Exercise 2', 'prescription': 'Rotate returner every 10 points'},
                {'name': 'Exercise 3', 'prescription': 'Serve-and-poach sequences'},
                {'name': 'Exercise 4', 'prescription': 'Alternate net player every game'},
                {'name': 'Exercise 5', 'prescription': 'Return-and-lob scenarios'},
                {'name': 'Exercise 6', 'prescription': 'Continuous serve-return drills'},
                {'name': 'Exercise 7', 'prescription': 'Rotate formations every five games'},
                {'name': 'Exercise 8', 'prescription': 'Rotating doubles points'}],
  'focus': 'doubles serve & return patterns'},
 {'sport': 'tennis',
  'name': 'Doubles Serve & Return Patterns - Four Players',
  'category': 'Doubles Serve & Return Patterns',
  'training_type': 'doubles',
  'participants': 'four_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': 'Full serve-return games'},
                {'name': 'Exercise 2', 'prescription': 'Alternate Australian and standard formations'},
                {'name': 'Exercise 3', 'prescription': 'Poaching after second serves'},
                {'name': 'Exercise 4', 'prescription': 'Return-only games'},
                {'name': 'Exercise 5', 'prescription': 'Communication after every point'},
                {'name': 'Exercise 6', 'prescription': 'Alternate aggressive and defensive returns'},
                {'name': 'Exercise 7', 'prescription': 'Doubles games beginning with second serves only'},
                {'name': 'Exercise 8', 'prescription': 'Full competitive doubles match'}],
  'focus': 'doubles serve & return patterns'},
 {'sport': 'tennis',
  'name': 'Doubles Net Domination - Just Me',
  'category': 'Doubles Net Domination',
  'training_type': 'doubles',
  'participants': 'alone',
  'exercises': [{'name': 'Exercise 1', 'prescription': '120 volley combination shadows'},
                {'name': 'Exercise 2', 'prescription': '80 overhead recoveries'},
                {'name': 'Exercise 3', 'prescription': '80 poach movement shadows'},
                {'name': 'Exercise 4', 'prescription': '40 net-to-net center-line sprints'},
                {'name': 'Exercise 5', 'prescription': '5 minutes net split-step timing'},
                {'name': 'Exercise 6', 'prescription': '100 reaction volley shadows'},
                {'name': 'Exercise 7', 'prescription': 'Diagonal coverage movement practice'},
                {'name': 'Exercise 8', 'prescription': 'Continuous net footwork finish'}],
  'focus': 'doubles net domination'},
 {'sport': 'tennis',
  'name': 'Doubles Net Domination - My Partner and I',
  'category': 'Doubles Net Domination',
  'training_type': 'doubles',
  'participants': 'pair',
  'exercises': [{'name': 'Exercise 1', 'prescription': '150 continuous volley exchanges'},
                {'name': 'Exercise 2', 'prescription': 'Alternating poaches every third volley'},
                {'name': 'Exercise 3', 'prescription': '80 reps: one volleys while other covers lobs'},
                {'name': 'Exercise 4', 'prescription': 'Alternate overhead smashes after every lob'},
                {'name': 'Exercise 5', 'prescription': '100 close-range reaction volleys'},
                {'name': 'Exercise 6', 'prescription': 'Volley-only doubles games'},
                {'name': 'Exercise 7', 'prescription': 'Alternate net player every game'},
                {'name': 'Exercise 8', 'prescription': 'Full doubles set emphasizing net dominance'}],
  'focus': 'doubles net domination'},
 {'sport': 'tennis',
  'name': 'Doubles Net Domination - Three Players',
  'category': 'Doubles Net Domination',
  'training_type': 'doubles',
  'participants': 'three_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': 'One baseline player versus pair at net'},
                {'name': 'Exercise 2', 'prescription': 'Rotate baseline player every game'},
                {'name': 'Exercise 3', 'prescription': 'Coordinated poaching practice'},
                {'name': 'Exercise 4', 'prescription': 'Alternate overhead coverage duties'},
                {'name': 'Exercise 5', 'prescription': 'Continuous net-pressure drills'},
                {'name': 'Exercise 6', 'prescription': 'Intercept crosscourt balls'},
                {'name': 'Exercise 7', 'prescription': 'Rotate after every 10 points'},
                {'name': 'Exercise 8', 'prescription': 'Competitive doubles rotations'}],
  'focus': 'doubles net domination'},
 {'sport': 'tennis',
  'name': 'Doubles Net Domination - Four Players',
  'category': 'Doubles Net Domination',
  'training_type': 'doubles',
  'participants': 'four_players',
  'exercises': [{'name': 'Exercise 1', 'prescription': 'Both teams approach net after every serve'},
                {'name': 'Exercise 2', 'prescription': 'Poach every second point'},
                {'name': 'Exercise 3', 'prescription': 'Volley-only games to 11'},
                {'name': 'Exercise 4', 'prescription': 'Overhead coverage after every lob'},
                {'name': 'Exercise 5', 'prescription': 'Alternate formations each game'},
                {'name': 'Exercise 6', 'prescription': '10 minutes rapid-fire reaction volleys'},
                {'name': 'Exercise 7', 'prescription': 'Best-of-three doubles match emphasizing net control'},
                {'name': 'Exercise 8', 'prescription': 'Full competitive doubles match with unrestricted tactics'}],
  'focus': 'doubles net domination'}]

WORKOUTS = TENNIS_SESSIONS
SESSIONS = TENNIS_SESSIONS


def get_sessions() -> List[Dict[str, Any]]:
    return TENNIS_SESSIONS


def get_workouts() -> List[Dict[str, Any]]:
    return TENNIS_SESSIONS


def get_sessions_by_category(category: str) -> List[Dict[str, Any]]:
    key = category.lower()
    return [item for item in TENNIS_SESSIONS if item.get("category", "").lower() == key]


def get_sessions_by_participants(participants: str) -> List[Dict[str, Any]]:
    key = participants.lower()
    return [item for item in TENNIS_SESSIONS if item.get("participants", "").lower() == key]


def get_session_names() -> List[str]:
    return [item["name"] for item in TENNIS_SESSIONS]


__all__ = [
    "SPORT",
    "SPORT_NAME",
    "TENNIS_SESSIONS",
    "WORKOUTS",
    "SESSIONS",
    "get_sessions",
    "get_workouts",
    "get_sessions_by_category",
    "get_sessions_by_participants",
    "get_session_names",
]
