"""Triathlon training catalog for Sportze.AI.

This module contains triathlon workouts and exercises codified from the Sportze.AI
training catalog. It is import-safe and ready for catalog manager integration.
"""

from __future__ import annotations

from typing import Any, Dict, List

SPORT = "triathlon"
SPORT_NAME = "Triathlon"


def exercise(name: str, prescription: str, notes: str | None = None) -> Dict[str, Any]:
    item: Dict[str, Any] = {"name": name, "prescription": prescription}
    if notes:
        item["notes"] = notes
    return item


def session(
    name: str,
    category: str,
    training_type: str,
    participants: str,
    exercises: List[Dict[str, Any]],
    level: str | None = None,
    focus: str | None = None,
    distance: str | None = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "sport": SPORT,
        "name": name,
        "category": category,
        "training_type": training_type,
        "participants": participants,
        "exercises": exercises,
    }
    if level:
        data["level"] = level
    if focus:
        data["focus"] = focus
    if distance:
        data["distance"] = distance
    return data


TRIATHLON_SESSIONS: List[Dict[str, Any]] = [{'sport': 'triathlon',
  'name': 'Learn How To Do Triathlon',
  'category': 'Learn How To Do Triathlon',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'First Mini Triathlon',
                 'prescription': '200 m swim + 5 min rest + 5 km bike + 3 min rest + 1 km run',
                 'notes': 'Keep all efforts easy and comfortable.'},
                {'name': 'Basic Swimming Endurance',
                 'prescription': '8 x 50 m freestyle; rest 30 sec',
                 'notes': 'Focus on smooth breathing every 2 or 3 strokes.'},
                {'name': 'Comfortable Bike Ride',
                 'prescription': 'Cycle 15 km on flat terrain',
                 'notes': 'Maintain 80-90 RPM at easy aerobic effort.'},
                {'name': 'Easy Continuous Run',
                 'prescription': 'Run 3 km continuously',
                 'notes': 'Conversational pace; do not sprint the finish.'},
                {'name': 'First Brick Session',
                 'prescription': 'Cycle 8 km + transition under 3 min + run 1.5 km',
                 'notes': 'Focus on adapting to heavy-leg feeling.'},
                {'name': 'Transition Practice',
                 'prescription': '5 full transition rounds',
                 'notes': 'Put on/remove swim gear, helmet, cycling shoes/equipment, running '
                          'shoes; time each round.'},
                {'name': 'Swimming Technique Session',
                 'prescription': '4 x 50 m easy freestyle + 4 x 50 m pull buoy + 4 x 50 m '
                                 'long-stroke focus; rest 20 sec'},
                {'name': 'Cadence Introduction',
                 'prescription': 'Cycle 20 km',
                 'notes': 'Every 5 km ride 2 min at 95-100 RPM, then return to normal cadence.'},
                {'name': 'Run Form Session',
                 'prescription': 'Run 4 km',
                 'notes': 'Every 500 m do 30 sec quicker shorter strides, then return to normal '
                          'pace.'},
                {'name': 'Swim + Bike Combination',
                 'prescription': '400 m continuous swim + 5 min rest + 10 km bike',
                 'notes': 'Maintain energy across both disciplines.'},
                {'name': 'Bike + Run Combination',
                 'prescription': 'Cycle 15 km + immediate transition + run 3 km',
                 'notes': 'Keep both disciplines easy aerobic.'},
                {'name': 'Learn Your First Race',
                 'prescription': '400 m swim + transition + 10 km bike + transition + 2 km run',
                 'notes': 'Practice pacing, nutrition, hydration, and transitions without '
                          'racing.'}],
  'level': 'learn'},
 {'sport': 'triathlon',
  'name': 'Beginner Exercises',
  'category': 'Beginner',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Beginner Endurance Triathlon',
                 'prescription': '600 m swim + transition + 20 km bike + transition + 5 km run',
                 'notes': 'Maintain Zone 2 effort throughout.'},
                {'name': 'Swim Endurance Builder',
                 'prescription': '300 m warm-up + 6 x 100 m freestyle + 200 m cooldown; total '
                                 '1,100 m',
                 'notes': 'Rest 20 sec after each 100 m.'},
                {'name': 'Bike Endurance Builder',
                 'prescription': 'Ride 30 km',
                 'notes': 'Every 10 km increase effort for 5 min, then return easy; maintain 85-95 '
                          'RPM.'},
                {'name': 'Beginner Running Endurance',
                 'prescription': 'Run 7 km continuously',
                 'notes': 'Increase pace slightly during final 2 km while holding form.'},
                {'name': 'Brick Progression',
                 'prescription': 'Cycle 25 km + transition under 2 min + run 5 km',
                 'notes': 'Keep run pace consistent start to finish.'},
                {'name': 'Swim Speed Introduction',
                 'prescription': '200 m warm-up + 10 x 100 m at 80% + 200 m cooldown',
                 'notes': 'Rest 15 sec after each 100 m.'},
                {'name': 'Cycling Power Session',
                 'prescription': 'Ride 35 km with 6 x 3 min high effort',
                 'notes': 'Recover 3 min easy between intervals.'},
                {'name': 'Tempo Running',
                 'prescription': '2 km easy + 5 km tempo + 2 km easy',
                 'notes': 'Total: 9 km.'},
                {'name': 'Long Brick',
                 'prescription': '800 m swim + transition + 30 km bike + transition + 6 km run',
                 'notes': 'Smooth pacing; avoid maximal effort.'},
                {'name': 'Transition Efficiency Session',
                 'prescription': '6 full transitions plus 300 m run after each',
                 'notes': 'Simulate race layout and make each transition faster without mistakes.'},
                {'name': 'Race Pace Simulation',
                 'prescription': '750 m swim + transition + 20 km bike + transition + 5 km run',
                 'notes': 'Expected Sprint Triathlon race pace; focus on pacing and nutrition.'},
                {'name': 'Endurance Challenge',
                 'prescription': '1,000 m swim + transition + 40 km bike + transition + 10 km run',
                 'notes': 'Confidence-building effort; fuel every 20-30 min on bike and hydrate '
                          'consistently.'}],
  'level': 'beginner'},
 {'sport': 'triathlon',
  'name': 'Super Sprint Triathlon - Swimming-only',
  'category': 'Super Sprint Triathlon',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'Super Sprint Race Pace Repeats',
                 'prescription': '200 m warm-up + 8 x 100 m race pace + 200 m cooldown',
                 'notes': 'Rest 20 sec between repeats.'},
                {'name': 'Fast Start Simulation',
                 'prescription': '200 m warm-up + 10 x 50 m',
                 'notes': 'First 15 m max effort, remaining 35 m race pace; rest 30 sec.'},
                {'name': 'Continuous Threshold Swim',
                 'prescription': '800 m continuous',
                 'notes': 'Increase speed every 200 m; final 200 m at race effort.'},
                {'name': 'Sighting Practice',
                 'prescription': '10 x 75 m',
                 'notes': 'Sight every 8 strokes; rest 20 sec.'},
                {'name': 'High Turnover Session',
                 'prescription': '12 x 50 m',
                 'notes': 'Higher-than-normal stroke rate; rest 20 sec.'},
                {'name': 'Sprint Finish Practice',
                 'prescription': '6 x 150 m',
                 'notes': 'First 100 m controlled, final 50 m maximal; rest 30 sec.'},
                {'name': 'Open Water Preparation',
                 'prescription': '1,200 m continuous',
                 'notes': 'Change pace every 200 m and practice bilateral breathing.'},
                {'name': 'Super Sprint Swim Test',
                 'prescription': '300 m warm-up + timed 400 m + 200 m cooldown'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': '400 m swim'},
 {'sport': 'triathlon',
  'name': 'Super Sprint Triathlon - Cycling-only',
  'category': 'Super Sprint Triathlon',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Race Cadence Ride',
                 'prescription': 'Ride 20 km',
                 'notes': 'Maintain 90-100 RPM at expected race intensity.'},
                {'name': 'Acceleration Intervals',
                 'prescription': '15 km ride',
                 'notes': 'Every 2 km sprint 30 sec, then return steady.'},
                {'name': 'Short Hill Repeats',
                 'prescription': '8 x 300-500 m hill climbs',
                 'notes': 'Ride down for recovery.'},
                {'name': 'Speed Maintenance',
                 'prescription': 'Ride 25 km',
                 'notes': 'Every 5 km ride 3 min above race pace.'},
                {'name': 'High Cadence Session',
                 'prescription': 'Ride 18 km',
                 'notes': 'Alternate 2 min at 105 RPM and 3 min normal cadence.'},
                {'name': 'Time Trial Practice',
                 'prescription': '5 km warm-up + 10 km max sustainable + 5 km cooldown'},
                {'name': 'Cornering Session',
                 'prescription': 'Ride 20 km loop with multiple turns',
                 'notes': 'Brake late, exit smoothly, maintain speed.'},
                {'name': 'Super Sprint Bike Test',
                 'prescription': 'Timed 10 km continuous effort',
                 'notes': 'Record average speed.'}],
  'level': 'specialized',
  'focus': 'Cycling-only',
  'distance': '10 km bike'},
 {'sport': 'triathlon',
  'name': 'Super Sprint Triathlon - Running-only',
  'category': 'Super Sprint Triathlon',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Race Pace Repeats',
                 'prescription': '2 km warm-up + 6 x 800 m race pace + 1 km cooldown',
                 'notes': 'Recover 90 sec walking.'},
                {'name': 'Sprint Finish Session',
                 'prescription': 'Run 5 km',
                 'notes': 'Final 200 m of each km near sprint effort.'},
                {'name': 'Fast Strides',
                 'prescription': '4 km easy',
                 'notes': 'Every 500 m do 20-sec stride.'},
                {'name': 'Negative Split Run',
                 'prescription': 'Run 6 km',
                 'notes': 'Each km slightly faster than previous.'},
                {'name': 'Hill Running',
                 'prescription': '10 x 150 m uphill',
                 'notes': 'Walk down for recovery.'},
                {'name': 'Cadence Builder',
                 'prescription': 'Run 5 km',
                 'notes': 'Quick light foot turnover; minimize ground contact.'},
                {'name': 'Threshold Run',
                 'prescription': '2 km easy + 4 km comfortably hard + 1 km easy'},
                {'name': 'Super Sprint Run Test',
                 'prescription': 'Timed 2.5 km effort',
                 'notes': 'Aim for even pacing.'}],
  'level': 'specialized',
  'focus': 'Running-only',
  'distance': '2.5 km run'},
 {'sport': 'triathlon',
  'name': 'Super Sprint Triathlon - Full Triathlon',
  'category': 'Super Sprint Triathlon',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Mini Race Simulation',
                 'prescription': '300 m swim + transition + 8 km bike + transition + 2 km run'},
                {'name': 'Bike-to-Run Brick',
                 'prescription': '15 km bike + immediate transition + 3 km race-pace run'},
                {'name': 'Swim-to-Bike Brick',
                 'prescription': '600 m swim + transition + 15 km bike'},
                {'name': 'Triple Brick', 'prescription': '3 rounds of 5 km bike + 1 km run'},
                {'name': 'Race Transition Session',
                 'prescription': '400 m swim + transition + 10 km bike + transition + 2.5 km run',
                 'notes': 'Focus on efficient transitions.'},
                {'name': 'Endurance Builder',
                 'prescription': '800 m swim + 20 km bike + 5 km run',
                 'notes': 'Zone 2 throughout.'},
                {'name': 'Speed Brick',
                 'prescription': '10 km bike race pace + transition + 2 km run race pace'},
                {'name': 'Full Super Sprint Mock Race',
                 'prescription': '400 m swim + transition + 10 km bike + transition + 2.5 km run',
                 'notes': 'Treat exactly like race day with equipment, pacing, hydration, and '
                          'transitions.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': '400 m / 10 km / 2.5 km'},
 {'sport': 'triathlon',
  'name': 'Sprint Triathlon - Swimming-only',
  'category': 'Sprint Triathlon',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'Sprint Race Pace Repeats',
                 'prescription': '300 m warm-up + 8 x 150 m race pace + 200 m cooldown',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Long Continuous Swim',
                 'prescription': '1,500 m continuous',
                 'notes': 'Steady aerobic pace; sight every 10 strokes.'},
                {'name': 'Threshold Intervals',
                 'prescription': '200 m warm-up + 10 x 100 m threshold + 200 m cooldown',
                 'notes': 'Rest 15 sec.'},
                {'name': 'Fast Start Session',
                 'prescription': '10 x 75 m',
                 'notes': 'First 25 m all-out, remaining 50 m race pace; rest 25 sec.'},
                {'name': 'Pull Endurance',
                 'prescription': '12 x 100 m pull buoy',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Tempo Swim',
                 'prescription': '1,200 m',
                 'notes': 'Increase pace every 300 m; final 300 m race effort.'},
                {'name': 'Open Water Simulation',
                 'prescription': '1,600 m continuous',
                 'notes': 'Every 200 m accelerate 20 m.'},
                {'name': 'Sprint Swim Time Trial',
                 'prescription': '300 m warm-up + timed 750 m + 300 m cooldown'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': '750 m swim'},
 {'sport': 'triathlon',
  'name': 'Sprint Triathlon - Cycling-only',
  'category': 'Sprint Triathlon',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Sprint Race Ride',
                 'prescription': 'Ride 30 km',
                 'notes': 'Hold expected Sprint race effort.'},
                {'name': 'Sweet Spot Session',
                 'prescription': '35 km with 5 x 6 min sweet spot',
                 'notes': '3 min easy between intervals.'},
                {'name': 'Time Trial Practice',
                 'prescription': '8 km warm-up + 20 km race pace + 5 km cooldown'},
                {'name': 'Hill Strength Ride',
                 'prescription': '30 km with 8 climbs of 2-4 min',
                 'notes': 'Recover on descents.'},
                {'name': 'Cadence Pyramid',
                 'prescription': '25 km ride',
                 'notes': 'Cycle 2 min at 80/90/100/90 RPM repeatedly.'},
                {'name': 'Power Surges',
                 'prescription': 'Ride 30 km',
                 'notes': 'Every 5 km ride 1 min at 110% race effort.'},
                {'name': 'Long Aerobic Ride',
                 'prescription': 'Ride 45 km Zone 2',
                 'notes': 'Hydrate every 15 min.'},
                {'name': 'Sprint Bike Time Trial',
                 'prescription': 'Timed 20 km max sustainable',
                 'notes': 'Record speed, cadence, and heart rate if available.'}],
  'level': 'specialized',
  'focus': 'Cycling-only',
  'distance': '20 km bike'},
 {'sport': 'triathlon',
  'name': 'Sprint Triathlon - Running-only',
  'category': 'Sprint Triathlon',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Sprint Tempo Run',
                 'prescription': '2 km warm-up + 5 km race pace + 1 km cooldown'},
                {'name': 'Interval Session',
                 'prescription': '2 km warm-up + 8 x 800 m faster than race pace + 1 km cooldown',
                 'notes': 'Recover 90 sec.'},
                {'name': 'Long Aerobic Run', 'prescription': 'Run 10 km Zone 2'},
                {'name': 'Progressive Run',
                 'prescription': 'Run 8 km',
                 'notes': 'Increase pace every 2 km; final 2 km race effort.'},
                {'name': 'Hill Repeats',
                 'prescription': '12 x 200 m uphill',
                 'notes': 'Walk or jog downhill.'},
                {'name': 'Cadence Run',
                 'prescription': 'Run 6 km',
                 'notes': 'Quick efficient turnover at moderate effort.'},
                {'name': 'Threshold Session',
                 'prescription': '2 km warm-up + 6 km comfortably hard + 2 km cooldown'},
                {'name': 'Sprint Run Time Trial',
                 'prescription': 'Timed 5 km',
                 'notes': 'Even pace start to finish.'}],
  'level': 'specialized',
  'focus': 'Running-only',
  'distance': '5 km run'},
 {'sport': 'triathlon',
  'name': 'Sprint Triathlon - Full Triathlon',
  'category': 'Sprint Triathlon',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Sprint Race Simulation',
                 'prescription': '600 m swim + transition + 18 km bike + transition + 4 km run'},
                {'name': 'Bike-to-Run Brick',
                 'prescription': '30 km bike + immediate 6 km race-pace run'},
                {'name': 'Swim-to-Bike Brick',
                 'prescription': '1,000 m swim + transition + 25 km bike'},
                {'name': 'Triple Brick',
                 'prescription': '3 rounds: 10 km bike + 2 km run',
                 'notes': 'Minimize transition time.'},
                {'name': 'Transition Efficiency Session',
                 'prescription': '750 m swim + transition + 20 km bike + transition + 5 km run',
                 'notes': 'Time transitions and improve composure.'},
                {'name': 'Endurance Session',
                 'prescription': '1,500 m swim + 45 km bike + 10 km run',
                 'notes': 'Zone 2; practice fueling/hydration.'},
                {'name': 'Race Pace Brick',
                 'prescription': '20 km bike race pace + immediate 5 km run race pace',
                 'notes': 'Maintain consistent effort.'},
                {'name': 'Full Sprint Mock Race',
                 'prescription': '750 m swim + transition + 20 km bike + transition + 5 km run',
                 'notes': 'Full race rehearsal with equipment, transition setup, and nutrition.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': '750 m / 20 km / 5 km'},
 {'sport': 'triathlon',
  'name': 'Olympic Triathlon - Swimming-only',
  'category': 'Olympic Triathlon',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'Olympic Race Pace Repeats',
                 'prescription': '400 m warm-up + 8 x 200 m race pace + 300 m cooldown',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Long Continuous Endurance',
                 'prescription': '2,500 m continuous',
                 'notes': 'Every 500 m accelerate 30 m; sight every 10 strokes.'},
                {'name': 'Threshold Builder',
                 'prescription': '300 m warm-up + 10 x 200 m threshold + 300 m cooldown',
                 'notes': 'Rest 15 sec.'},
                {'name': 'Negative Split Swim',
                 'prescription': '2,000 m continuous',
                 'notes': 'Each 500 m faster.'},
                {'name': 'Pull Endurance',
                 'prescription': '12 x 200 m pull buoy',
                 'notes': 'Rest 20 sec; long efficient strokes.'},
                {'name': 'Open Water Simulation',
                 'prescription': '2,200 m continuous',
                 'notes': 'Every 400 m sprint 40 m then race pace.'},
                {'name': 'Tempo Endurance',
                 'prescription': '300 m warm-up + 1,800 m tempo + 300 m cooldown'},
                {'name': 'Olympic Swim Time Trial',
                 'prescription': '500 m warm-up + timed 1,500 m + 300 m cooldown'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': '1.5 km swim'},
 {'sport': 'triathlon',
  'name': 'Olympic Triathlon - Cycling-only',
  'category': 'Olympic Triathlon',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Olympic Race Ride',
                 'prescription': 'Ride 55 km',
                 'notes': 'Hold expected Olympic race power/effort; use aero position.'},
                {'name': 'Sweet Spot Endurance',
                 'prescription': '60 km with 5 x 10 min sweet spot',
                 'notes': '5 min easy between intervals.'},
                {'name': 'Time Trial Session',
                 'prescription': '10 km warm-up + 40 km race pace + 5 km cooldown'},
                {'name': 'Hill Strength Session',
                 'prescription': '55 km with 8 climbs of 4-6 min',
                 'notes': 'Recover on descents.'},
                {'name': 'Cadence Builder',
                 'prescription': '50 km ride',
                 'notes': 'Alternate 5 min at 80/90/100 RPM repeatedly.'},
                {'name': 'Power Surges',
                 'prescription': 'Ride 50 km',
                 'notes': 'Every 8 km ride 2 min above race effort.'},
                {'name': 'Long Aerobic Ride',
                 'prescription': 'Ride 70 km Zone 2',
                 'notes': 'Fluids every 15 min; nutrition every 30 min.'},
                {'name': 'Olympic Bike Time Trial',
                 'prescription': 'Timed 40 km max sustainable',
                 'notes': 'Record speed, cadence, heart rate.'}],
  'level': 'specialized',
  'focus': 'Cycling-only',
  'distance': '40 km bike'},
 {'sport': 'triathlon',
  'name': 'Olympic Triathlon - Running-only',
  'category': 'Olympic Triathlon',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Olympic Tempo Run',
                 'prescription': '3 km warm-up + 10 km race pace + 2 km cooldown'},
                {'name': 'Threshold Intervals',
                 'prescription': '2 km warm-up + 6 x 1 km faster than race pace + 2 km cooldown',
                 'notes': 'Recover 2 min jogging.'},
                {'name': 'Long Aerobic Run', 'prescription': 'Run 15 km Zone 2'},
                {'name': 'Progressive Run',
                 'prescription': 'Run 12 km',
                 'notes': 'Increase pace every 3 km; finish at race effort.'},
                {'name': 'Hill Repeats',
                 'prescription': '10 x 400 m uphill',
                 'notes': 'Jog downhill.'},
                {'name': 'Cadence Session',
                 'prescription': 'Run 10 km',
                 'notes': 'Quick efficient foot turnover.'},
                {'name': 'Threshold Run',
                 'prescription': '3 km warm-up + 8 km comfortably hard + 2 km cooldown'},
                {'name': 'Olympic Run Time Trial',
                 'prescription': 'Timed 10 km',
                 'notes': 'Even pacing.'}],
  'level': 'specialized',
  'focus': 'Running-only',
  'distance': '10 km run'},
 {'sport': 'triathlon',
  'name': 'Olympic Triathlon - Full Triathlon',
  'category': 'Olympic Triathlon',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Olympic Simulation',
                 'prescription': '1,200 m swim + transition + 35 km bike + transition + 8 km run'},
                {'name': 'Olympic Brick',
                 'prescription': '50 km bike + immediate 10 km race-pace run'},
                {'name': 'Swim-Bike Brick',
                 'prescription': '2,000 m swim + transition + 45 km bike'},
                {'name': 'Double Brick',
                 'prescription': '2 rounds: 20 km bike + 5 km run',
                 'notes': 'Minimize transition time.'},
                {'name': 'Transition Practice',
                 'prescription': '1,500 m swim + transition + 40 km bike + transition + 10 km run',
                 'notes': 'Focus on smooth transitions.'},
                {'name': 'Endurance Builder',
                 'prescription': '2,500 m swim + 60 km bike + 12 km run',
                 'notes': 'Zone 2 throughout.'},
                {'name': 'Race Pace Brick',
                 'prescription': '40 km bike race pace + immediate 10 km run race pace'},
                {'name': 'Full Olympic Mock Race',
                 'prescription': '1,500 m swim + transition + 40 km bike + transition + 10 km run',
                 'notes': 'Execute nutrition, pacing, hydration, equipment, and transitions as '
                          'planned.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': '1.5 km / 40 km / 10 km'},
 {'sport': 'triathlon',
  'name': 'Half Ironman (70.3) - Swimming-only',
  'category': 'Half Ironman (70.3)',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'Half Ironman Race Pace Repeats',
                 'prescription': '500 m warm-up + 8 x 300 m race pace + 300 m cooldown',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Long Continuous Swim',
                 'prescription': '3,500 m continuous',
                 'notes': 'Every 500 m perform 50 m acceleration; sight every 10 strokes.'},
                {'name': 'Threshold Session',
                 'prescription': '400 m warm-up + 10 x 200 m threshold + 400 m cooldown',
                 'notes': 'Rest 15 sec.'},
                {'name': 'Negative Split Swim',
                 'prescription': '3,000 m',
                 'notes': 'Increase pace every 750 m.'},
                {'name': 'Pull Endurance',
                 'prescription': '15 x 200 m pull buoy',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Open Water Simulation',
                 'prescription': '3,200 m continuous',
                 'notes': 'Every 600 m sprint 50 m then race pace.'},
                {'name': 'Tempo Endurance',
                 'prescription': '500 m warm-up + 2,500 m tempo + 500 m cooldown'},
                {'name': 'Half Ironman Swim Time Trial',
                 'prescription': '500 m warm-up + timed 1,900 m + 400 m cooldown'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': '1.9 km swim'},
 {'sport': 'triathlon',
  'name': 'Half Ironman (70.3) - Cycling-only',
  'category': 'Half Ironman (70.3)',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Half Ironman Race Ride',
                 'prescription': 'Ride 110 km',
                 'notes': 'Hold expected Half Ironman race effort; aero when practical.'},
                {'name': 'Sweet Spot Builder',
                 'prescription': '100 km with 6 x 12 min sweet spot',
                 'notes': '5 min easy between efforts.'},
                {'name': 'Time Trial Session',
                 'prescription': '10 km warm-up + 70 km race pace + 10 km cooldown'},
                {'name': 'Hill Endurance',
                 'prescription': '100 km with 10 climbs of 5-8 min',
                 'notes': 'Recover on descents.'},
                {'name': 'Cadence Builder',
                 'prescription': '80 km ride',
                 'notes': 'Alternate 10 min at 80/90/100 RPM repeatedly.'},
                {'name': 'Power Surges',
                 'prescription': 'Ride 90 km',
                 'notes': 'Every 15 km ride 3 min above race effort.'},
                {'name': 'Long Aerobic Ride',
                 'prescription': 'Ride 130 km Zone 2',
                 'notes': 'Nutrition every 30 min; hydration every 15 min.'},
                {'name': 'Half Ironman Bike Time Trial',
                 'prescription': 'Timed 90 km at max sustainable race effort',
                 'notes': 'Record speed, cadence, heart rate, and nutrition timing.'}],
  'level': 'specialized',
  'focus': 'Cycling-only',
  'distance': '90 km bike'},
 {'sport': 'triathlon',
  'name': 'Half Ironman (70.3) - Running-only',
  'category': 'Half Ironman (70.3)',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Half Ironman Tempo Run',
                 'prescription': '3 km warm-up + 18 km race pace + 2 km cooldown'},
                {'name': 'Threshold Intervals',
                 'prescription': '3 km warm-up + 8 x 2 km slightly faster than race pace + 2 km '
                                 'cooldown',
                 'notes': 'Recover 2 min jogging.'},
                {'name': 'Long Aerobic Run', 'prescription': 'Run 24 km Zone 2'},
                {'name': 'Progressive Long Run',
                 'prescription': 'Run 20 km',
                 'notes': 'Increase pace every 5 km; finish at race effort.'},
                {'name': 'Hill Strength Session',
                 'prescription': '12 x 500 m uphill',
                 'notes': 'Jog downhill.'},
                {'name': 'Cadence Builder',
                 'prescription': 'Run 18 km',
                 'notes': 'Quick efficient cadence, controlled effort.'},
                {'name': 'Threshold Endurance',
                 'prescription': '3 km warm-up + 15 km comfortably hard + 2 km cooldown'},
                {'name': 'Half Ironman Run Time Trial',
                 'prescription': 'Timed half marathon 21.1 km',
                 'notes': 'Maintain even pace.'}],
  'level': 'specialized',
  'focus': 'Running-only',
  'distance': '21.1 km run'},
 {'sport': 'triathlon',
  'name': 'Half Ironman (70.3) - Full Triathlon',
  'category': 'Half Ironman (70.3)',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Half Ironman Simulation',
                 'prescription': '1,500 m swim + transition + 75 km bike + transition + 16 km run'},
                {'name': 'Long Brick',
                 'prescription': '90 km bike + immediate 15 km run race pace'},
                {'name': 'Swim-Bike Brick',
                 'prescription': '2,500 m swim + transition + 80 km bike'},
                {'name': 'Double Brick',
                 'prescription': '2 rounds: 40 km bike + 8 km run',
                 'notes': 'Keep transitions under 2 minutes.'},
                {'name': 'Transition Practice',
                 'prescription': '1,900 m swim + transition + 90 km bike + transition + 21.1 km '
                                 'run',
                 'notes': 'Race-day execution.'},
                {'name': 'Endurance Builder',
                 'prescription': '3,000 m swim + 120 km bike + 18 km run',
                 'notes': 'Zone 2; practice fueling and hydration.'},
                {'name': 'Race Pace Brick',
                 'prescription': '90 km bike race pace + immediate 18 km run race pace',
                 'notes': 'Hold pacing despite fatigue.'},
                {'name': 'Full Half Ironman Mock Race',
                 'prescription': '1,900 m swim + transition + 90 km bike + transition + 21.1 km '
                                 'run',
                 'notes': 'Complete dress rehearsal with exact equipment, pacing, nutrition, '
                          'hydration, and setup.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': '1.9 km / 90 km / 21.1 km'},
 {'sport': 'triathlon',
  'name': 'Ironman (140.6) - Swimming-only',
  'category': 'Ironman (140.6)',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'Ironman Race Pace Repeats',
                 'prescription': '500 m warm-up + 8 x 500 m race pace + 500 m cooldown',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Long Continuous Endurance Swim',
                 'prescription': '5,500 m continuous',
                 'notes': 'Every 1,000 m accelerate 100 m; sight every 10 strokes.'},
                {'name': 'Threshold Builder',
                 'prescription': '500 m warm-up + 12 x 300 m threshold + 500 m cooldown',
                 'notes': 'Rest 20 sec.'},
                {'name': 'Negative Split Swim',
                 'prescription': '4,500 m continuous',
                 'notes': 'Increase pace every 1,125 m; final quarter race effort.'},
                {'name': 'Pull Endurance',
                 'prescription': '15 x 300 m pull buoy',
                 'notes': 'Rest 20 sec; long relaxed stroke.'},
                {'name': 'Open Water Simulation',
                 'prescription': '4,500 m continuous',
                 'notes': 'Every 800 m sprint 50 m; practice sighting and bilateral breathing.'},
                {'name': 'Ironman Tempo Swim',
                 'prescription': '500 m warm-up + 3,500 m tempo + 500 m cooldown'},
                {'name': 'Ironman Swim Time Trial',
                 'prescription': '500 m warm-up + timed 3,800 m + 500 m cooldown'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': '3.8 km swim'},
 {'sport': 'triathlon',
  'name': 'Ironman (140.6) - Cycling-only',
  'category': 'Ironman (140.6)',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Ironman Race Ride',
                 'prescription': 'Ride 200 km',
                 'notes': 'Hold Ironman race zone; aero when practical; nutrition every 30 min.'},
                {'name': 'Sweet Spot Endurance',
                 'prescription': '140 km with 6 x 20 min sweet spot',
                 'notes': '10 min easy between intervals.'},
                {'name': 'Long Time Trial',
                 'prescription': '10 km warm-up + 120 km race pace + 10 km cooldown'},
                {'name': 'Hill Endurance Ride',
                 'prescription': '160 km with 10 climbs of 8-10 min',
                 'notes': 'Recover on descents.'},
                {'name': 'Cadence Builder',
                 'prescription': '120 km ride',
                 'notes': 'Alternate 15 min at 80/90/100 RPM repeatedly.'},
                {'name': 'Power Surge Ride',
                 'prescription': '150 km',
                 'notes': 'Every 20 km ride 5 min slightly above race effort.'},
                {'name': 'Ultra Endurance Ride',
                 'prescription': '220 km Zone 2',
                 'notes': 'Carbs every 25-30 min; hydrate every 15 min.'},
                {'name': 'Ironman Bike Time Trial',
                 'prescription': 'Timed 180 km at Ironman race pace',
                 'notes': 'Record speed, cadence, heart rate, nutrition, and hydration.'}],
  'level': 'specialized',
  'focus': 'Cycling-only',
  'distance': '180 km bike'},
 {'sport': 'triathlon',
  'name': 'Ironman (140.6) - Running-only',
  'category': 'Ironman (140.6)',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Ironman Tempo Run',
                 'prescription': '5 km warm-up + 30 km marathon pace + 2 km cooldown'},
                {'name': 'Threshold Intervals',
                 'prescription': '3 km warm-up + 8 x 3 km faster than marathon pace + 2 km '
                                 'cooldown',
                 'notes': 'Recover 3 min jogging.'},
                {'name': 'Long Aerobic Run', 'prescription': 'Run 35 km Zone 2'},
                {'name': 'Progressive Long Run',
                 'prescription': 'Run 32 km',
                 'notes': 'Increase pace every 8 km; final 8 km Ironman race pace.'},
                {'name': 'Hill Endurance',
                 'prescription': '10 x 1 km uphill',
                 'notes': 'Jog downhill.'},
                {'name': 'Cadence Builder',
                 'prescription': 'Run 24 km',
                 'notes': 'Quick efficient cadence, controlled effort.'},
                {'name': 'Marathon Pace Builder',
                 'prescription': '5 km warm-up + 25 km marathon pace + 2 km cooldown'},
                {'name': 'Ironman Run Time Trial',
                 'prescription': 'Timed marathon 42.2 km',
                 'notes': 'Focus on pacing, nutrition, and hydration.'}],
  'level': 'specialized',
  'focus': 'Running-only',
  'distance': '42.2 km run'},
 {'sport': 'triathlon',
  'name': 'Ironman (140.6) - Full Triathlon',
  'category': 'Ironman (140.6)',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'Ironman Simulation',
                 'prescription': '3,000 m swim + transition + 140 km bike + transition + 25 km '
                                 'run'},
                {'name': 'Long Brick',
                 'prescription': '180 km bike + immediate 20 km run race pace'},
                {'name': 'Swim-Bike Brick',
                 'prescription': '4,000 m swim + transition + 120 km bike'},
                {'name': 'Double Brick',
                 'prescription': '2 rounds: 60 km bike + 10 km run',
                 'notes': 'Keep transitions under 2 minutes.'},
                {'name': 'Transition Practice',
                 'prescription': '3,800 m swim + transition + 180 km bike + transition + 42.2 km '
                                 'run',
                 'notes': 'Treat exactly as race day.'},
                {'name': 'Ultra Endurance Builder',
                 'prescription': '4,500 m swim + 160 km bike + 25 km run',
                 'notes': 'Zone 2; practice complete nutrition strategy.'},
                {'name': 'Race Pace Brick',
                 'prescription': '140 km bike race pace + immediate 25 km run race pace',
                 'notes': 'Maintain effort and fueling discipline.'},
                {'name': 'Full Ironman Mock Race',
                 'prescription': '3,800 m swim + transition + 180 km bike + transition + 42.2 km '
                                 'run',
                 'notes': 'Use complete race-day setup, clothing, transition layout, nutrition, '
                          'hydration, and pacing.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': '3.8 km / 180 km / 42.2 km'},
 {'sport': 'triathlon',
  'name': 'XTERRA - Swimming-only',
  'category': 'XTERRA',
  'training_type': 'swimming',
  'participants': 'alone',
  'exercises': [{'name': 'XTERRA Open Water Repeats',
                 'prescription': '8 x 300 m open water',
                 'notes': 'Rest 30 sec; sight every 8-10 strokes.'},
                {'name': 'Continuous Open Water Swim',
                 'prescription': '2,500 m continuous',
                 'notes': 'Change pace every 500 m; swim straight.'},
                {'name': 'Buoy Turn Practice',
                 'prescription': '12 x 100 m',
                 'notes': 'Perform tight buoy turn each rep; rest 20 sec.'},
                {'name': 'Rough Water Adaptation',
                 'prescription': '2,000 m in choppy conditions if available',
                 'notes': 'Maintain technique despite waves.'},
                {'name': 'Fast Start Session',
                 'prescription': '12 x 100 m',
                 'notes': 'First 25 m sprint, remaining 75 m race pace; rest 20 sec.'},
                {'name': 'Long Tempo Swim',
                 'prescription': '3,000 m continuous',
                 'notes': 'Comfortably hard pace.'},
                {'name': 'Sighting Endurance',
                 'prescription': '2,500 m',
                 'notes': 'Sight every 6 strokes while minimizing lift.'},
                {'name': 'XTERRA Swim Time Trial',
                 'prescription': 'Timed 1,500 m open-water effort',
                 'notes': 'Record time and pacing.'}],
  'level': 'specialized',
  'focus': 'Swimming-only',
  'distance': 'open-water swim'},
 {'sport': 'triathlon',
  'name': 'XTERRA - Mountain Bike-only',
  'category': 'XTERRA',
  'training_type': 'cycling',
  'participants': 'alone',
  'exercises': [{'name': 'Technical Trail Ride',
                 'prescription': '30 km single-track trails',
                 'notes': 'Focus on cornering, braking, climbing, and line selection.'},
                {'name': 'Climbing Session',
                 'prescription': '10 technical climbs of 3-5 min',
                 'notes': 'Descend carefully between reps.'},
                {'name': 'Descending Skills',
                 'prescription': '60 min descending practice',
                 'notes': 'Work body position, braking, corner exits.'},
                {'name': 'Long Trail Endurance', 'prescription': '60 km MTB trails Zone 2'},
                {'name': 'Technical Intervals',
                 'prescription': '40 km ride',
                 'notes': 'Every 5 km ride next technical section at max sustainable speed.'},
                {'name': 'Rock Garden Practice',
                 'prescription': '15 rock garden repetitions',
                 'notes': 'Maintain momentum and line choice.'},
                {'name': 'Mixed Terrain Ride',
                 'prescription': '70 km gravel/dirt/forest/single-track',
                 'notes': 'Adapt cadence and body position.'},
                {'name': 'XTERRA MTB Time Trial',
                 'prescription': 'Timed 40 km off-road race effort',
                 'notes': 'Record time and average speed.'}],
  'level': 'specialized',
  'focus': 'Mountain Bike-only',
  'distance': 'off-road MTB'},
 {'sport': 'triathlon',
  'name': 'XTERRA - Trail Running-only',
  'category': 'XTERRA',
  'training_type': 'running',
  'participants': 'alone',
  'exercises': [{'name': 'Trail Tempo Run',
                 'prescription': '12 km trail run at race pace',
                 'notes': 'Maintain rhythm over uneven terrain.'},
                {'name': 'Hill Repeats',
                 'prescription': '12 x 300 m uphill trail',
                 'notes': 'Jog downhill.'},
                {'name': 'Technical Descents',
                 'prescription': '45 min downhill running practice',
                 'notes': 'Focus on foot placement and controlled speed.'},
                {'name': 'Long Trail Run', 'prescription': '20 km varied trails Zone 2'},
                {'name': 'Progressive Trail Run',
                 'prescription': '16 km',
                 'notes': 'Increase pace every 4 km.'},
                {'name': 'Agility Trail Session',
                 'prescription': '10 km trail run',
                 'notes': 'Every 1 km perform 20 quick lateral hops over marker/obstacle.'},
                {'name': 'Technical Terrain Endurance',
                 'prescription': '18 km technical terrain',
                 'notes': 'Rocks, roots, climbs, descents; prioritize smooth foot placement.'},
                {'name': 'XTERRA Trail Time Trial',
                 'prescription': 'Timed 10 km trail race effort',
                 'notes': 'Record time and pacing.'}],
  'level': 'specialized',
  'focus': 'Trail Running-only',
  'distance': 'trail run'},
 {'sport': 'triathlon',
  'name': 'XTERRA - Full Triathlon',
  'category': 'XTERRA',
  'training_type': 'mixed',
  'participants': 'alone',
  'exercises': [{'name': 'XTERRA Simulation',
                 'prescription': '1,200 m open-water swim + transition + 25 km MTB + transition + '
                                 '8 km trail run'},
                {'name': 'MTB-to-Trail Brick',
                 'prescription': '40 km MTB + immediate 10 km trail run'},
                {'name': 'Swim-MTB Brick',
                 'prescription': '2,000 m open-water swim + transition + 35 km MTB'},
                {'name': 'Double Brick',
                 'prescription': '2 rounds: 20 km MTB + 5 km trail run',
                 'notes': 'Keep transitions short.'},
                {'name': 'Transition Practice',
                 'prescription': '1,500 m open-water swim + transition + 35 km MTB + transition + '
                                 '10 km trail run',
                 'notes': 'Smooth equipment changes and efficient pacing.'},
                {'name': 'XTERRA Endurance Builder',
                 'prescription': '2,500 m open-water swim + 50 km MTB + 15 km trail run',
                 'notes': 'Zone 2; adapt to terrain.'},
                {'name': 'Race Pace Brick',
                 'prescription': '35 km MTB race pace + immediate 10 km trail run race pace'},
                {'name': 'Full XTERRA Mock Race',
                 'prescription': 'Open-water swim + transition + MTB course + transition + trail '
                                 'run',
                 'notes': 'Use planned race equipment, nutrition, hydration, setup, and pacing in '
                          'realistic off-road conditions.'}],
  'level': 'specialized',
  'focus': 'Full Triathlon',
  'distance': 'off-road triathlon'}]

WORKOUTS = TRIATHLON_SESSIONS
SESSIONS = TRIATHLON_SESSIONS


def get_sessions() -> List[Dict[str, Any]]:
    return TRIATHLON_SESSIONS


def get_workouts() -> List[Dict[str, Any]]:
    return TRIATHLON_SESSIONS


def get_sessions_by_category(category: str) -> List[Dict[str, Any]]:
    key = category.lower().strip()
    return [s for s in TRIATHLON_SESSIONS if s.get("category", "").lower() == key]


def get_sessions_by_focus(focus: str) -> List[Dict[str, Any]]:
    key = focus.lower().strip()
    return [s for s in TRIATHLON_SESSIONS if s.get("focus", "").lower() == key]


def get_sessions_by_training_type(training_type: str) -> List[Dict[str, Any]]:
    key = training_type.lower().strip()
    return [s for s in TRIATHLON_SESSIONS if s.get("training_type", "").lower() == key]


def get_sessions_by_distance(distance: str) -> List[Dict[str, Any]]:
    key = distance.lower().strip()
    return [s for s in TRIATHLON_SESSIONS if key in s.get("distance", "").lower()]


def validate_catalog() -> bool:
    required = {"sport", "name", "category", "training_type", "participants", "exercises"}
    for s in TRIATHLON_SESSIONS:
        if not required.issubset(s):
            return False
        if s["sport"] != SPORT or not s["exercises"]:
            return False
        for e in s["exercises"]:
            if "name" not in e or "prescription" not in e:
                return False
    return True


__all__ = [
    "SPORT",
    "SPORT_NAME",
    "TRIATHLON_SESSIONS",
    "WORKOUTS",
    "SESSIONS",
    "exercise",
    "session",
    "get_sessions",
    "get_workouts",
    "get_sessions_by_category",
    "get_sessions_by_focus",
    "get_sessions_by_training_type",
    "get_sessions_by_distance",
    "validate_catalog",
]
