"""Volleyball training catalog for Sportze.AI.

This module contains volleyball workouts and exercises codified from the
Sportze.AI training catalog. It is import-safe and ready for catalog manager
integration.
"""

from __future__ import annotations

from typing import Any, Dict, List

SPORT = "volleyball"
SPORT_NAME = "Volleyball"


def exercise(name: str, prescription: str, notes: str | None = None) -> Dict[str, Any]:
    item: Dict[str, Any] = {"name": name, "prescription": prescription}
    if notes:
        item["notes"] = notes
    return item


def session(
    name: str,
    category: str,
    training_type: str,
    participants: str,
    exercises: List[Dict[str, Any]],
    level: str | None = None,
    focus: str | None = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "sport": SPORT,
        "name": name,
        "category": category,
        "training_type": training_type,
        "participants": participants,
        "exercises": exercises,
    }
    if level:
        data["level"] = level
    if focus:
        data["focus"] = focus
    return data


VOLLEYBALL_SESSIONS: List[Dict[str, Any]] = [{'category': 'Learn How To Play',
  'exercises': [{'name': 'Self Toss & Catch',
                 'notes': 'Toss the ball about 2 meters above your head, let it drop, and catch it '
                          'with both hands.',
                 'prescription': '75 reps'},
                {'name': 'Continuous Self Forearm Passes',
                 'notes': 'Forearm pass vertically to yourself without catching it; restart if it '
                          'hits the ground.',
                 'prescription': '40 consecutive touches'},
                {'name': 'Continuous Self Overhead Sets',
                 'notes': 'Perform overhead sets to yourself.',
                 'prescription': '50 consecutive contacts'},
                {'name': 'Alternate Pass and Set',
                 'notes': 'Alternate one forearm pass and one overhead set continuously.',
                 'prescription': '100 total contacts'},
                {'name': 'Wall Forearm Passing',
                 'notes': 'Stand 2.5 meters from a wall and forearm pass against it.',
                 'prescription': '120 passes'},
                {'name': 'Wall Overhead Setting',
                 'notes': 'Set against the wall continuously.',
                 'prescription': '150 contacts'},
                {'name': 'Target Wall Passing',
                 'notes': 'Tape a square target on the wall and hit it using forearm passes.',
                 'prescription': '40 target hits'},
                {'name': 'Wall Setting Accuracy',
                 'notes': 'Set into a taped square on the wall.',
                 'prescription': '60 target sets'},
                {'name': 'Standing Serve Practice',
                 'notes': 'Serve into a marked area on a wall or fence.',
                 'prescription': '40 serves'},
                {'name': 'Overhand Serve Introduction',
                 'notes': 'Focus on proper contact instead of power.',
                 'prescription': '30 serves'},
                {'name': 'Footwork Box Drill',
                 'notes': 'Shuffle around four cones arranged in a square.',
                 'prescription': '10 complete laps'},
                {'name': 'Volleyball Ready Position Holds',
                 'notes': 'Rest 15 seconds between rounds.',
                 'prescription': '5 x 45 sec'},
                {'name': 'Approach Footwork Practice',
                 'notes': 'Practice the correct three-step approach without jumping.',
                 'prescription': '40 reps'},
                {'name': 'Jump Reach Practice',
                 'notes': 'Perform your attack approach and jump to touch the highest point '
                          'possible.',
                 'prescription': '20 jumps'},
                {'name': 'Ball Control Circuit',
                 'notes': '20 self passes; 20 self sets; 10 pass-set combinations.',
                 'prescription': '5 rounds'}],
  'focus': 'fundamentals',
  'level': 'learn',
  'name': 'Learn How To Play - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Beginner',
  'exercises': [{'name': '200 Continuous Ball Contacts',
                 'notes': 'Keep the ball alive using any legal touch.',
                 'prescription': '200 total contacts'},
                {'name': 'Wall Passing Ladder',
                 'notes': '30 forearm passes; 30 overhead sets; 30 alternating contacts.',
                 'prescription': '3 rounds'},
                {'name': 'Accuracy Passing Challenge',
                 'notes': 'Hit five different wall targets 15 times each.',
                 'prescription': '75 target hits'},
                {'name': 'Overhand Serving Repetitions',
                 'notes': 'Aim at different court zones.',
                 'prescription': '60 serves'},
                {'name': 'Deep Serve Challenge',
                 'notes': 'Serve to the back third of the court.',
                 'prescription': '25 serves'},
                {'name': 'Short Serve Challenge',
                 'notes': 'Serve just behind the attack line.',
                 'prescription': '25 serves'},
                {'name': 'Approach Jump Series',
                 'notes': 'Complete attack approaches with explosive jumps.',
                 'prescription': '30 reps'},
                {'name': 'Block Jump Technique',
                 'notes': 'Use proper arm extension.',
                 'prescription': '40 jumps'},
                {'name': 'Defensive Movement Circuit',
                 'notes': 'Move forward, backward, left, and right from defensive position, '
                          'returning to center each time.',
                 'prescription': '40 total movements'},
                {'name': 'One-Hand Ball Control',
                 'notes': 'Tap the ball upward using one hand only.',
                 'prescription': '40 contacts per hand'},
                {'name': 'Passing Endurance',
                 'notes': 'Complete with as few mistakes as possible.',
                 'prescription': '400 wall passes'},
                {'name': 'Setting Endurance',
                 'notes': 'Stop only to retrieve the ball.',
                 'prescription': '500 wall sets'},
                {'name': 'Reaction Toss',
                 'notes': 'Throw high against the wall, react to rebound, and control before the '
                          'second bounce.',
                 'prescription': '50 reps'},
                {'name': 'Serve Accuracy Ladder',
                 'notes': 'Left corner x10; right corner x10; deep middle x10; short left x10; '
                          'short right x10.',
                 'prescription': '50 target serves'},
                {'name': 'Complete Ball Control Circuit',
                 'notes': '50 self sets; 50 self passes; 25 alternating contacts; 20 serves; 15 '
                          'approach jumps.',
                 'prescription': '3 rounds'}],
  'focus': 'fundamentals',
  'level': 'beginner',
  'name': 'Beginner - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Setter Training',
  'exercises': [{'name': 'Wall Setting Marathon',
                 'notes': 'Maintain consistent height.',
                 'prescription': '600 consecutive wall sets'},
                {'name': 'One-Hand Setting Control',
                 'notes': 'Use right and left hand against the wall.',
                 'prescription': '80 each hand'},
                {'name': 'Quick Release Sets',
                 'notes': 'Stand close to the wall with minimal contact time.',
                 'prescription': '250 rapid sets'},
                {'name': 'High Ball Simulation',
                 'notes': 'Set at least 4 meters high, reposition underneath, and repeat.',
                 'prescription': '60 reps'},
                {'name': 'Long-Distance Setting',
                 'notes': 'Set high across about 8 meters toward a target.',
                 'prescription': '50 sets'},
                {'name': 'Side Movement Setting',
                 'notes': 'Shuffle three steps left, set, shuffle three steps right, set again.',
                 'prescription': '80 sets'},
                {'name': 'Backward Setting Practice',
                 'notes': 'Face away from the wall and set over your head toward the wall.',
                 'prescription': '120 back sets'},
                {'name': 'Jump Setting',
                 'notes': 'Focus on balanced takeoff and soft hands.',
                 'prescription': '80 jump sets'},
                {'name': 'Setter Footwork Circuit',
                 'notes': 'Move around four cones in a setter pattern before wall setting.',
                 'prescription': '40 reps'},
                {'name': 'Target Precision Setting',
                 'notes': 'Tape five targets and hit each 20 times.',
                 'prescription': '100 target sets'},
                {'name': 'Transition Simulation',
                 'notes': 'Start lying down, stand quickly, move to ball, set, and return to '
                          'ground.',
                 'prescription': '30 reps'},
                {'name': 'Complete Setter Circuit',
                 'notes': '75 wall sets; 30 jump sets; 20 back sets; 20 long-distance sets.',
                 'prescription': '3 rounds'}],
  'focus': 'Setter Training',
  'name': 'Setter Training - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Outside Hitter Training',
  'exercises': [{'name': 'Full Attack Approach',
                 'notes': 'Complete three- or four-step attack approaches with explosive jump and '
                          'arm swing.',
                 'prescription': '60 reps'},
                {'name': 'Wall Spike Contacts',
                 'notes': 'Hit against the wall using full attacking motion.',
                 'prescription': '120 spikes'},
                {'name': 'Cross-Court Arm Swing Practice',
                 'notes': 'Aim diagonal spikes toward a marked wall target.',
                 'prescription': '60 attacks'},
                {'name': 'Line Shot Practice',
                 'notes': 'Hit straight-line attacks against a narrow wall target.',
                 'prescription': '60 attacks'},
                {'name': 'Tip Shot Practice',
                 'notes': 'Use controlled tip shots against the wall into a marked zone.',
                 'prescription': '80 tips'},
                {'name': 'Serve Receive Simulation',
                 'notes': 'Self-toss away, move quickly into position, and forearm pass.',
                 'prescription': '80 reps'},
                {'name': 'Transition Footwork',
                 'notes': 'Defensive stance to attack approach, jump, recover, and return to '
                          'defense.',
                 'prescription': '50 reps'},
                {'name': 'Block-to-Attack Transition',
                 'notes': 'Blocking jump then immediately attack approach and jump.',
                 'prescription': '40 reps'},
                {'name': 'Jump Reach Series',
                 'notes': 'Maximum vertical jumps using attack approach.',
                 'prescription': '30 jumps'},
                {'name': 'Serve and Attack Sequence',
                 'notes': 'Serve, retrieve, complete attack approach, and spike against wall.',
                 'prescription': '40 sequences'},
                {'name': 'Attack Endurance Circuit',
                 'notes': '25 spikes; 15 tips; 15 line shots; 15 cross-court shots.',
                 'prescription': '4 rounds'},
                {'name': 'Complete Outside Hitter Circuit',
                 'notes': '20 serves; 30 wall spikes; 20 serve receives; 20 approach jumps; 15 '
                          'transition drills.',
                 'prescription': '3 rounds'}],
  'focus': 'Outside Hitter Training',
  'name': 'Outside Hitter Training - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Opposite Hitter',
  'exercises': [{'name': 'Right-Side Attack Repetitions',
                 'notes': 'Complete right-side attack approaches with full arm swing against a '
                          'wall.',
                 'prescription': '70 reps'},
                {'name': 'Power Spike Series',
                 'notes': 'Spike against a wall at maximum controlled power.',
                 'prescription': '120 spikes'},
                {'name': 'High Ball Attack Practice',
                 'notes': 'Self-toss high, approach, and attack at the highest contact point.',
                 'prescription': '50 reps'},
                {'name': 'Backcourt Attack Footwork',
                 'notes': 'Start behind attack line, three-step approach, jump, and simulate '
                          'back-row attack.',
                 'prescription': '60 reps'},
                {'name': 'Line Attack Accuracy',
                 'notes': 'Mark a narrow wall target and hit it with full attacks.',
                 'prescription': '50 hits'},
                {'name': 'Deep Cross-Court Attack',
                 'notes': 'Aim powerful diagonal attacks into a marked deep-court target.',
                 'prescription': '60 reps'},
                {'name': 'Attack After Block Simulation',
                 'notes': 'Block jump, transition into full attacking approach, and spike.',
                 'prescription': '45 reps'},
                {'name': 'Jump Power Circuit',
                 'notes': '10 attack jumps; 10 squat jumps; 10 broad jumps.',
                 'prescription': '4 rounds'},
                {'name': 'Serve Power Practice',
                 'notes': 'Maximum pace while maintaining control.',
                 'prescription': '70 serves'},
                {'name': 'Defensive Recovery Drill',
                 'notes': 'Dive or sprawl, recover immediately, then attack approach.',
                 'prescription': '30 reps'},
                {'name': 'Endurance Attack Ladder',
                 'notes': '20 spikes; 20 approach jumps; 20 tip shots; 20 serves.',
                 'prescription': '3 rounds'},
                {'name': 'Complete Opposite Circuit',
                 'notes': '25 spikes; 15 line attacks; 15 cross-court attacks; 10 back-row '
                          'attacks; 10 serves.',
                 'prescription': '4 rounds'}],
  'focus': 'Opposite Hitter',
  'name': 'Opposite Hitter - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Middle Blocker',
  'exercises': [{'name': 'Block Jump Repetitions',
                 'notes': 'Extend both hands fully over an imaginary net.',
                 'prescription': '100 jumps'},
                {'name': 'Lateral Blocking Footwork',
                 'notes': 'Shuffle left, block jump, shuffle right, block jump.',
                 'prescription': '80 jumps'},
                {'name': 'Triple Block Movement',
                 'notes': 'Move from left block to center block to right block continuously.',
                 'prescription': '50 cycles'},
                {'name': 'Quick Attack Footwork',
                 'notes': 'Practice quick middle attack approaches without ball.',
                 'prescription': '80 reps'},
                {'name': 'Quick Attack Wall Hits',
                 'notes': 'Self-toss low, quick attack approach, and spike against wall.',
                 'prescription': '70 reps'},
                {'name': 'Read-and-Jump Simulation',
                 'notes': 'Toss randomly to different wall spots, react, and block jump.',
                 'prescription': '60 reps'},
                {'name': 'Penetration Blocking Drill',
                 'notes': 'Press hands over imaginary net during every block jump.',
                 'prescription': '80 reps'},
                {'name': 'Transition Drill',
                 'notes': 'Block jump, shuffle backward, quick attack approach, jump.',
                 'prescription': '50 reps'},
                {'name': 'Continuous Explosive Jumps',
                 'notes': 'Rest only after completing the set.',
                 'prescription': '40 jumps'},
                {'name': 'Block Reach Challenge',
                 'notes': 'Touch maximum vertical reach and record best mark.',
                 'prescription': '30 attempts'},
                {'name': 'Middle Endurance Circuit',
                 'notes': '20 block jumps; 20 quick approaches; 15 lateral shuffles.',
                 'prescription': '5 rounds'},
                {'name': 'Complete Middle Blocker Circuit',
                 'notes': '25 block jumps; 20 quick attacks; 20 transition drills; 15 explosive '
                          'jumps.',
                 'prescription': '4 rounds'}],
  'focus': 'Middle Blocker',
  'name': 'Middle Blocker - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Libero',
  'exercises': [{'name': 'Wall Dig Marathon',
                 'notes': 'Forearm pass against the wall consecutively.',
                 'prescription': '500 contacts'},
                {'name': 'Low Defensive Shuffle',
                 'notes': 'Remain in defensive position while shuffling between four cones.',
                 'prescription': '8 minutes'},
                {'name': 'Self Dig Practice',
                 'notes': 'Throw high, allow one bounce, then controlled dig.',
                 'prescription': '80 reps'},
                {'name': 'Reaction Wall Drill',
                 'notes': 'Throw hard against wall, react to unpredictable rebound, dig before '
                          'second bounce.',
                 'prescription': '60 reps'},
                {'name': 'Dive Technique Practice',
                 'notes': 'Recover to feet immediately after each controlled dive.',
                 'prescription': '40 dives'},
                {'name': 'Pancake Simulation',
                 'notes': 'Practice sliding one hand beneath a rolling ball.',
                 'prescription': '40 reps'},
                {'name': 'Defensive Recovery Circuit',
                 'notes': 'Dive, recover, shuffle 3 meters, then forearm pass.',
                 'prescription': '40 reps'},
                {'name': 'Passing Precision',
                 'notes': 'Hit taped wall target using forearm passes.',
                 'prescription': '120 target passes'},
                {'name': 'Short Reaction Toss',
                 'notes': 'Stand 1.5 meters from wall, throw rapidly, control every rebound.',
                 'prescription': '150 contacts'},
                {'name': 'Endurance Passing Ladder',
                 'notes': '100 forearm passes; 100 overhead contacts; 100 alternating contacts.',
                 'prescription': '2 rounds'},
                {'name': 'Court Coverage Drill',
                 'notes': 'Sprint to five semicircle cones, return to center, simulate dig.',
                 'prescription': '10 circuits'},
                {'name': 'Complete Libero Circuit',
                 'notes': '50 digs; 50 wall passes; 20 dives; 20 reaction throws.',
                 'prescription': '4 rounds'}],
  'focus': 'Libero',
  'name': 'Libero - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Serving Specialist',
  'exercises': [{'name': 'Deep Corner Serving',
                 'notes': '30 deep left corner and 30 deep right corner.',
                 'prescription': '60 serves'},
                {'name': 'Short Zone Serving',
                 'notes': 'Target just behind the attack line.',
                 'prescription': '60 serves'},
                {'name': 'Float Serve Repetitions',
                 'notes': 'Emphasize minimal ball spin.',
                 'prescription': '80 serves'},
                {'name': 'Jump Float Practice',
                 'notes': 'Consistent contact and placement.',
                 'prescription': '60 serves'},
                {'name': 'Power Jump Serve',
                 'notes': 'Maximum controlled power.',
                 'prescription': '50 serves'},
                {'name': 'Zone Accuracy Challenge',
                 'notes': 'Zones 1 through 6 x10 each.',
                 'prescription': '60 serves'},
                {'name': 'Consecutive Accuracy Test',
                 'notes': 'Restart after every miss.',
                 'prescription': '15 consecutive target serves'},
                {'name': 'Pressure Serving',
                 'notes': 'Every missed target adds one extra serve at the end.',
                 'prescription': '25 target serves plus misses'},
                {'name': 'Long-to-Short Alternating',
                 'notes': 'Alternate deep and short serves.',
                 'prescription': '60 serves'},
                {'name': 'Fatigue Serving',
                 'notes': '10 burpees then 5 serves while maintaining accuracy.',
                 'prescription': '8 rounds'},
                {'name': 'Serve Endurance Ladder',
                 'notes': '20 float serves; 20 jump floats; 20 jump serves.',
                 'prescription': '2 rounds'},
                {'name': 'Complete Serving Specialist Circuit',
                 'notes': '20 deep serves; 20 short serves; 20 float serves; 20 jump serves; 20 '
                          'target serves.',
                 'prescription': '2 rounds'}],
  'focus': 'Serving Specialist',
  'name': 'Serving Specialist - Training Alone',
  'participants': 'alone',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Learn How To Play',
  'exercises': [{'name': 'Partner Forearm Passing',
                 'notes': 'Stand 3-4 meters apart without ball touching floor.',
                 'prescription': '150 consecutive passes'},
                {'name': 'Partner Overhead Setting',
                 'notes': 'Set back and forth with partner.',
                 'prescription': '150 consecutive sets'},
                {'name': 'Pass-Set Alternation',
                 'notes': 'Player A forearm passes, Player B overhead sets; alternate roles after '
                          'every contact.',
                 'prescription': '200 total contacts'},
                {'name': 'Pepper Drill',
                 'notes': 'Pass, set, controlled attack continuously.',
                 'prescription': '8 minutes'},
                {'name': 'Serve to Partner Target',
                 'notes': 'Partner catches each ball inside marked target zone.',
                 'prescription': '50 serves'},
                {'name': 'Passing Accuracy Challenge',
                 'notes': 'One player serves while the other passes into a 2-meter target area, '
                          'then switch.',
                 'prescription': '40 accurate passes each'},
                {'name': 'Setting Accuracy Challenge',
                 'notes': 'Partner tosses and setter targets hoop/marked area, then switch.',
                 'prescription': '60 accurate sets each'},
                {'name': 'Cooperative Rally',
                 'notes': 'Use only forearm passes and overhead sets.',
                 'prescription': '100 consecutive contacts'},
                {'name': 'Attack Footwork Practice',
                 'notes': 'Partner tosses high balls; attacker approaches and catches at peak '
                          'jump, then switch.',
                 'prescription': '40 reps each'},
                {'name': 'Controlled Spiking',
                 'notes': 'Partner tosses; attacker spikes toward designated floor target, then '
                          'switch.',
                 'prescription': '50 attacks each'},
                {'name': 'Blocking Timing Introduction',
                 'notes': 'One simulates attacker while other performs block jumps, then switch.',
                 'prescription': '40 reps each'},
                {'name': 'Court Movement Drill',
                 'notes': 'Partner calls five marked spots from defensive position, then switch.',
                 'prescription': '30 sequences each'},
                {'name': 'Mini Rally Challenge',
                 'notes': 'Half-court rallies count only if each team uses at least three '
                          'contacts.',
                 'prescription': '20 successful rallies'},
                {'name': 'Serve Receive Rotation',
                 'notes': 'Switch after every 10 serves.',
                 'prescription': '50 serves and 50 receptions each'},
                {'name': 'Complete Fundamentals Circuit',
                 'notes': '40 passes; 40 sets; 20 serves; 20 attacks; 20 defensive movements.',
                 'prescription': '3 rounds'}],
  'focus': 'fundamentals',
  'level': 'learn',
  'name': 'Learn How To Play - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Beginner',
  'exercises': [{'name': 'Continuous Pepper Challenge',
                 'notes': 'Restart timer if ball touches floor.',
                 'prescription': '12 uninterrupted minutes'},
                {'name': 'Three-Contact Rally',
                 'notes': 'Every rally must include pass, set, attack before crossing net.',
                 'prescription': '50 rallies'},
                {'name': 'Serve Accuracy Competition',
                 'notes': 'Serve into six court zones; one point per target.',
                 'prescription': '40 serves each'},
                {'name': 'Controlled Hitting Drill',
                 'notes': 'Attack to alternating cross-court and line targets, then switch.',
                 'prescription': '60 attacks each'},
                {'name': 'Passing Under Pressure',
                 'notes': 'Aggressive serve receive to setter target, then switch.',
                 'prescription': '50 accurate receptions each'},
                {'name': 'Transition Footwork',
                 'notes': 'Receive toss, transition to attack, approach, simulate spike, then '
                          'switch.',
                 'prescription': '40 reps each'},
                {'name': 'Block and Cover',
                 'notes': 'Block light attack and recover to defense, then switch.',
                 'prescription': '40 reps each'},
                {'name': 'Quick Reaction Defense',
                 'notes': 'Feeder throws left, right, short, and deep; defender controls every '
                          'ball.',
                 'prescription': '50 balls each'},
                {'name': 'Cooperative Attack Rally',
                 'notes': 'Every third contact must be an attack.',
                 'prescription': '30 rallies'},
                {'name': 'Deep Ball Recovery',
                 'notes': 'Pass deep free balls accurately, then switch.',
                 'prescription': '40 recoveries each'},
                {'name': 'Short Ball Recovery',
                 'notes': 'Recover short drops near net and pass accurately, then switch.',
                 'prescription': '40 reps each'},
                {'name': 'Serving Endurance',
                 'notes': '20 float serves; 20 power serves; 20 zone serves.',
                 'prescription': '60 serves each'},
                {'name': 'Attack Accuracy Ladder',
                 'notes': '10 line attacks; 10 cross-court attacks; 10 tips; 10 deep attacks.',
                 'prescription': '40 attacks each'},
                {'name': 'Full-Court Movement Drill',
                 'notes': 'Move between defense, block, attack approach, and serve receive while '
                          'partner feeds.',
                 'prescription': '10 minutes'},
                {'name': 'Complete Beginner Circuit',
                 'notes': '30 serves; 40 passes; 30 sets; 30 attacks; 20 blocks; 20 defensive '
                          'recoveries.',
                 'prescription': '3 rounds'}],
  'focus': 'fundamentals',
  'level': 'beginner',
  'name': 'Beginner - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Setter',
  'exercises': [{'name': 'Target Setting Accuracy',
                 'notes': 'Partner tosses from different locations; set into target zone.',
                 'prescription': '80 sets'},
                {'name': 'Moving Setter Drill',
                 'notes': 'Partner tosses randomly left/right/forward/backward; move and set '
                          'accurately.',
                 'prescription': '60 reps'},
                {'name': 'Back Set Practice',
                 'notes': 'Partner passes from backcourt; execute back sets to a hitting zone.',
                 'prescription': '60 sets'},
                {'name': 'Jump Setting',
                 'notes': 'Partner tosses above net; quick release and consistent height.',
                 'prescription': '70 jump sets'},
                {'name': 'Long-Distance Transition Setting',
                 'notes': 'Sprint from deep pass to deliver high outside set.',
                 'prescription': '50 reps'},
                {'name': 'Setter Decision Drill',
                 'notes': 'Partner calls outside/middle/opposite just before arrival.',
                 'prescription': '80 sets'},
                {'name': 'Low Pass Recovery',
                 'notes': 'Chase off-target pass and produce playable set.',
                 'prescription': '50 reps'},
                {'name': 'Quick Middle Connection',
                 'notes': 'Time quick tempo sets to middle hitter movement.',
                 'prescription': '60 quick sets'},
                {'name': 'Setter Conditioning Circuit',
                 'notes': '10 movement sets; 10 jump sets; 10 back sets.',
                 'prescription': '5 rounds'},
                {'name': 'Pressure Setting',
                 'notes': 'Partner varies pass quality every repetition.',
                 'prescription': '100 playable sets'},
                {'name': 'Serve Receive to Set Transition',
                 'notes': 'Partner serves; receive return pass and set attacking position.',
                 'prescription': '50 reps'},
                {'name': 'Complete Setter Circuit',
                 'notes': '20 target sets; 20 jump sets; 20 back sets; 20 recovery sets; 20 '
                          'transition sets.',
                 'prescription': '3 rounds'}],
  'focus': 'Setter',
  'name': 'Setter - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Outside Hitter',
  'exercises': [{'name': 'Cross-Court Attack Drill',
                 'notes': 'Partner sets from net; attack cross-court into target.',
                 'prescription': '60 spikes'},
                {'name': 'Line Attack Drill',
                 'notes': 'Partner sets; hit line attacks within one meter of sideline.',
                 'prescription': '60 attacks'},
                {'name': 'Tip Shot Practice',
                 'notes': 'Partner delivers attackable balls; tip into open zones.',
                 'prescription': '50 tips'},
                {'name': 'Serve Receive to Attack',
                 'notes': 'Receive serve, transition immediately, and spike next set.',
                 'prescription': '40 sequences'}],
  'focus': 'Outside Hitter',
  'name': 'Outside Hitter - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Opposite Hitter',
  'exercises': [{'name': 'Right-Side Power Attack',
                 'notes': 'Partner sets from front court; attack right side with controlled power.',
                 'prescription': '70 spikes'},
                {'name': 'High Ball Attack',
                 'notes': 'Partner delivers high outside sets; focus timing and extension.',
                 'prescription': '60 attacks'},
                {'name': 'Back Row Attack',
                 'notes': 'Start behind attack line while partner sets from net.',
                 'prescription': '50 attacks'},
                {'name': 'Line Attack Precision',
                 'notes': 'Hit right-side line attacks into target zone.',
                 'prescription': '50 attacks'},
                {'name': 'Cross-Court Power Drill',
                 'notes': 'Alternate deep corner and sharp angle.',
                 'prescription': '60 spikes'},
                {'name': 'Block Transition Attack',
                 'notes': 'Block jump, transition off net, receive set, and attack.',
                 'prescription': '40 reps'},
                {'name': 'Off-System Attack',
                 'notes': 'Score controlled attacks on imperfect sets.',
                 'prescription': '50 balls'},
                {'name': 'Serve-Attack Sequence',
                 'notes': 'Serve, recover, receive set, and spike.',
                 'prescription': '40 sequences'},
                {'name': 'Continuous Attack Rally',
                 'notes': 'Partner continuously sets attackable balls before switching.',
                 'prescription': '30 consecutive attacks'},
                {'name': 'Attack Endurance',
                 'notes': 'Partner provides continuous sets; maintain full-speed attacks.',
                 'prescription': '3 x 3 minutes'},
                {'name': 'Pressure Finishing Drill',
                 'notes': 'Attack around or over raised hands/blocking pad.',
                 'prescription': '50 attacks'},
                {'name': 'Complete Opposite Circuit',
                 'notes': '20 line attacks; 20 cross-court attacks; 15 back-row attacks; 15 '
                          'transition attacks; 10 serves.',
                 'prescription': '3 rounds'}],
  'focus': 'Opposite Hitter',
  'name': 'Opposite Hitter - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Middle Blocker',
  'exercises': [{'name': 'Single Block Timing',
                 'notes': 'Partner attacks from outside; time jump.',
                 'prescription': '60 blocks'},
                {'name': 'Lateral Block Movement',
                 'notes': 'Partner alternates tosses to left and right hitters.',
                 'prescription': '70 blocks'},
                {'name': 'Quick Attack Connection',
                 'notes': 'Partner acts as setter; time middle attacks.',
                 'prescription': '60 quick attacks'},
                {'name': 'Block-Recover-Attack',
                 'notes': 'Block jump, recover, then quick middle attack.',
                 'prescription': '50 reps'},
                {'name': 'Read Blocking',
                 'notes': 'Read line or cross-court attack from shoulder position.',
                 'prescription': '50 blocks'},
                {'name': 'Double Block Timing',
                 'notes': 'Coordinate with another blocker, then rotate positions.',
                 'prescription': '40 blocks'},
                {'name': 'Closing the Block',
                 'notes': 'Seal inside gap against attacks from both antennas.',
                 'prescription': '60 reps'},
                {'name': 'Transition Footwork',
                 'notes': 'Alternate blocking and attacking movements.',
                 'prescription': '50 reps'},
                {'name': 'Rapid Block Series',
                 'notes': 'Partner tosses attack balls without pause.',
                 'prescription': '4 x 25 jumps'},
                {'name': 'Quick Reaction Blocking',
                 'notes': 'Partner varies slow and fast approach tempo.',
                 'prescription': '60 blocks'},
                {'name': 'Net Control Drill',
                 'notes': 'Maintain correct blocking position against continuous attacks.',
                 'prescription': '5 minutes'},
                {'name': 'Complete Middle Circuit',
                 'notes': '20 single blocks; 20 lateral blocks; 20 quick attacks; 15 transition '
                          'drills; 15 read blocks.',
                 'prescription': '3 rounds'}],
  'focus': 'Middle Blocker',
  'name': 'Middle Blocker - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Libero',
  'exercises': [{'name': 'Serve Receive Repetitions',
                 'notes': 'Pass partner serves into setter target.',
                 'prescription': '80 receptions'},
                {'name': 'Digging Drill',
                 'notes': 'Dig controlled partner spikes accurately.',
                 'prescription': '70 digs'},
                {'name': 'Reaction Defense',
                 'notes': 'Defend unpredictable tips, rolls, and spikes.',
                 'prescription': '60 balls'},
                {'name': 'Diving Recovery',
                 'notes': 'Dive for short balls and recover immediately.',
                 'prescription': '40 reps'},
                {'name': 'Pancake Save Practice',
                 'notes': 'Partner hits low balls for pancake saves.',
                 'prescription': '30 saves'},
                {'name': 'Short vs Deep Defense',
                 'notes': 'Defend alternating short tips and deep attacks.',
                 'prescription': '60 balls'},
                {'name': 'Continuous Defensive Rally',
                 'notes': 'Keep continuous attacks playable.',
                 'prescription': '3 x 4 minutes'},
                {'name': 'Passing Accuracy Challenge',
                 'notes': 'Partner serves from alternating positions.',
                 'prescription': '70 perfect passes'},
                {'name': 'Emergency Recovery',
                 'notes': 'Recover and return awkward rebounds.',
                 'prescription': '50 balls'},
                {'name': 'Full Court Coverage',
                 'notes': 'Defend every zone across the full court.',
                 'prescription': '80 balls'},
                {'name': 'Defensive Endurance',
                 'notes': 'Partner feeds attack balls continuously.',
                 'prescription': '5 minutes'},
                {'name': 'Complete Libero Circuit',
                 'notes': '20 serve receptions; 20 digs; 15 dives; 15 emergency recoveries; 15 '
                          'reaction defenses.',
                 'prescription': '3 rounds'}],
  'focus': 'Libero',
  'name': 'Libero - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'},
 {'category': 'Serving Specialist',
  'exercises': [{'name': 'Deep Zone Serving',
                 'notes': '15 serves into each of six court zones.',
                 'prescription': '90 serves'},
                {'name': 'Float Serve Accuracy',
                 'notes': 'Partner stands in 2-meter target zone; serve within one step.',
                 'prescription': '60 serves'},
                {'name': 'Jump Serve Power',
                 'notes': 'Maximum speed while staying in bounds.',
                 'prescription': '50 serves'},
                {'name': 'Short Serve Placement',
                 'notes': 'Land just behind attack line.',
                 'prescription': '50 serves'},
                {'name': 'Receiver Target Drill',
                 'notes': 'Serve to make partner pass off target.',
                 'prescription': '40 off-target passes forced'},
                {'name': 'Weak Receiver Challenge',
                 'notes': 'Target partner weaker receiving side as they change position.',
                 'prescription': '50 serves'},
                {'name': 'Alternate Serve Types',
                 'notes': '20 float; 20 jump float; 20 jump serve.',
                 'prescription': '60 serves'},
                {'name': 'Pressure Serving',
                 'notes': 'Every miss adds another serve at the end.',
                 'prescription': '30 target serves plus misses'},
                {'name': 'Fatigue Serving',
                 'notes': '10 burpees then 5 serves.',
                 'prescription': '8 rounds'},
                {'name': 'Serve Under Pressure',
                 'notes': 'Every point begins with serve to designated target; miss loses point.',
                 'prescription': 'First to 21 points'},
                {'name': 'Tactical Serving',
                 'notes': 'Partner chooses receiving position; select and execute best serve.',
                 'prescription': '60 serves'},
                {'name': 'Complete Serving Specialist Circuit',
                 'notes': '20 float serves; 20 jump floats; 20 jump serves; 20 short serves; 20 '
                          'tactical serves.',
                 'prescription': '2 rounds'}],
  'focus': 'Serving Specialist',
  'name': 'Serving Specialist - Training With 2+ People',
  'participants': '2+ people',
  'sport': 'volleyball',
  'training_type': 'technical'}]


def get_sessions() -> List[Dict[str, Any]]:
    return VOLLEYBALL_SESSIONS


def get_workouts() -> List[Dict[str, Any]]:
    return get_sessions()


def get_exercises() -> List[Dict[str, Any]]:
    return [exercise for workout in VOLLEYBALL_SESSIONS for exercise in workout["exercises"]]


def get_sessions_by_category(category: str) -> List[Dict[str, Any]]:
    normalized = category.strip().lower()
    return [s for s in VOLLEYBALL_SESSIONS if s["category"].lower() == normalized]


def get_sessions_by_participants(participants: str) -> List[Dict[str, Any]]:
    normalized = participants.strip().lower()
    return [s for s in VOLLEYBALL_SESSIONS if s["participants"].lower() == normalized]


def get_session_names() -> List[str]:
    return [session["name"] for session in VOLLEYBALL_SESSIONS]


WORKOUTS = VOLLEYBALL_SESSIONS
SESSIONS = VOLLEYBALL_SESSIONS
EXERCISES = get_exercises()

__all__ = [
    "SPORT",
    "SPORT_NAME",
    "VOLLEYBALL_SESSIONS",
    "WORKOUTS",
    "SESSIONS",
    "EXERCISES",
    "get_sessions",
    "get_workouts",
    "get_exercises",
    "get_sessions_by_category",
    "get_sessions_by_participants",
    "get_session_names",
]
