"""Weightlifting training catalog for Sportze.AI.

This module contains weightlifting workouts and exercises codified from the
Sportze.AI training catalog. It is import-safe and ready for catalog manager
integration.
"""

from __future__ import annotations

from typing import Any, Dict, List

SPORT = "weightlifting"
SPORT_NAME = "Weightlifting"


def exercise(name: str, prescription: str, notes: str | None = None) -> Dict[str, Any]:
    item: Dict[str, Any] = {"name": name, "prescription": prescription}
    if notes:
        item["notes"] = notes
    return item


def session(
    name: str,
    category: str,
    training_type: str,
    participants: str,
    exercises: List[Dict[str, Any]],
    level: str | None = None,
    focus: str | None = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "sport": SPORT,
        "name": name,
        "category": category,
        "training_type": training_type,
        "participants": participants,
        "exercises": exercises,
    }
    if level:
        data["level"] = level
    if focus:
        data["focus"] = focus
    return data


WEIGHTLIFTING_SESSIONS: List[Dict[str, Any]] = [{'sport': 'weightlifting',
  'name': 'Learn How to Lift',
  'category': 'Learn How to Lift',
  'training_type': 'technical',
  'participants': 'alone',
  'exercises': [{'name': 'PVC Pipe Squats',
                 'prescription': '3 x 15',
                 'notes': 'Use a PVC pipe or empty bar; focus on depth, balance, and chest upright.'},
                {'name': 'Hip Hinge Drill',
                 'prescription': '3 x 15',
                 'notes': 'Hold a PVC pipe along your back and maintain head, upper back, and tailbone contact.'},
                {'name': 'Empty Bar Deadlifts',
                 'prescription': '4 x 10',
                 'notes': 'Emphasize setup and neutral spine.'},
                {'name': 'Empty Bar Bench Press', 'prescription': '4 x 12', 'notes': 'Control the bar throughout.'},
                {'name': 'Empty Bar Overhead Press',
                 'prescription': '4 x 10',
                 'notes': 'Keep core braced and bar path vertical.'},
                {'name': 'Front Rack Position Holds',
                 'prescription': '5 x 30 seconds',
                 'notes': 'Hold an empty bar in the front rack position.'},
                {'name': 'Overhead Stability Hold',
                 'prescription': '5 x 30 seconds',
                 'notes': 'Lock an empty bar overhead.'},
                {'name': 'Bodyweight Bracing Practice',
                 'prescription': '20 reps x 5-second holds',
                 'notes': 'Practice diaphragmatic brace-and-release.'},
                {'name': 'Squat Depth Practice',
                 'prescription': '50 bodyweight squats',
                 'notes': 'Pause 2 seconds at the bottom of every rep.'},
                {'name': 'Deadlift Setup Repetitions',
                 'prescription': '40 resets',
                 'notes': 'Practice setup without lifting the bar.'},
                {'name': 'Bar Path Drill',
                 'prescription': '30 slow deadlift reps',
                 'notes': 'Keep the bar in contact with your legs.'},
                {'name': 'Controlled Tempo Squats',
                 'prescription': '3 x 8',
                 'notes': '5-second descent, 2-second pause, controlled ascent.'},
                {'name': 'Bench Press Bar Control',
                 'prescription': '3 x 15',
                 'notes': 'Paused bench presses with 2-second pause on chest.'},
                {'name': 'Basic Lift Circuit',
                 'prescription': '4 rounds',
                 'notes': '10 squats, 10 deadlifts, 10 bench presses, 10 overhead presses with empty bar.'},
                {'name': 'Movement Pattern Circuit',
                 'prescription': '4 rounds',
                 'notes': '15 bodyweight squats, 15 hip hinges, 15 push-ups, 30-second overhead hold.'}],
  'level': 'learn',
  'focus': 'fundamental lifting movement patterns'},
 {'sport': 'weightlifting',
  'name': 'Beginner Weightlifting',
  'category': 'Beginner Weightlifting',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Back Squat Technique',
                 'prescription': '5 x 8 at 50–60% estimated 1RM',
                 'notes': 'Focus on consistent depth.'},
                {'name': 'Conventional Deadlift Technique',
                 'prescription': '5 x 6 at 55–65% effort',
                 'notes': 'Emphasize perfect form.'},
                {'name': 'Bench Press Technique',
                 'prescription': '5 x 8',
                 'notes': 'Controlled descent and explosive press.'},
                {'name': 'Strict Press', 'prescription': '4 x 8', 'notes': 'Avoid leg drive.'},
                {'name': 'Romanian Deadlift', 'prescription': '4 x 10', 'notes': 'Emphasize hamstring tension.'},
                {'name': 'Front Squat Introduction', 'prescription': '4 x 8', 'notes': 'Maintain high elbows.'},
                {'name': 'Pause Squats', 'prescription': '4 x 6', 'notes': 'Pause 3 seconds at the bottom.'},
                {'name': 'Paused Bench Press', 'prescription': '4 x 6', 'notes': 'Hold bar on chest for 2 seconds.'},
                {'name': 'Push Press Introduction', 'prescription': '4 x 8', 'notes': 'Use controlled leg drive.'},
                {'name': "Farmer's Carry",
                 'prescription': '6 x 30 meters',
                 'notes': 'Carry two heavy dumbbells or trap bars.'},
                {'name': 'Tempo Deadlift', 'prescription': '4 x 5', 'notes': 'Lower the bar over 4 seconds.'},
                {'name': 'Strength Ladder',
                 'prescription': '6 rounds',
                 'notes': '5 squats, 5 bench presses, 5 deadlifts using moderate weight.'},
                {'name': 'Compound Lift Circuit',
                 'prescription': '4 rounds',
                 'notes': '8 back squats, 8 bench presses, 8 Romanian deadlifts, 8 overhead presses.'},
                {'name': 'Core Stability Circuit',
                 'prescription': '4 rounds',
                 'notes': '45-second plank, 15 hanging knee raises, 20 back extensions.'},
                {'name': 'Beginner Total Body Session',
                 'prescription': '5 x 5 each',
                 'notes': 'Back squat, bench press, deadlift; rest 2–3 minutes between sets.'}],
  'level': 'beginner',
  'focus': 'beginner strength and barbell technique'},
 {'sport': 'weightlifting',
  'name': 'Squat Training',
  'category': 'Squat Training',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Heavy Back Squat',
                 'prescription': '5 x 5 at 80% 1RM',
                 'notes': 'Rest 3–4 minutes between sets.'},
                {'name': 'Front Squat Strength', 'prescription': '5 x 4 at 75–80% front squat 1RM'},
                {'name': 'Pause Back Squat', 'prescription': '4 x 5', 'notes': 'Pause 3 seconds at the bottom.'},
                {'name': 'Tempo Squat',
                 'prescription': '4 x 6',
                 'notes': 'Use a 5-second descent, then stand explosively.'},
                {'name': 'Box Squat',
                 'prescription': '5 x 5',
                 'notes': 'Sit lightly on the box before standing explosively.'},
                {'name': 'Pin Squat',
                 'prescription': '5 x 3',
                 'notes': 'Start from safety pins set at parallel depth.'},
                {'name': 'Overhead Squat',
                 'prescription': '4 x 6',
                 'notes': 'Emphasize balance and shoulder stability.'},
                {'name': 'Zercher Squat', 'prescription': '4 x 8', 'notes': 'Maintain an upright torso.'},
                {'name': 'High-Bar Volume Squat', 'prescription': '6 x 8 at 65–70% 1RM'},
                {'name': 'Low-Bar Strength Squat', 'prescription': '6 x 3 at 85% 1RM'},
                {'name': 'Squat Endurance Challenge',
                 'prescription': '100 back squats at 50% 1RM',
                 'notes': 'Use as few sets as possible.'},
                {'name': 'Complete Squat Circuit',
                 'prescription': '4 rounds',
                 'notes': '5 back squats, 5 front squats, 5 pause squats, 5 overhead squats.'}],
  'level': 'intermediate',
  'focus': 'squat training'},
 {'sport': 'weightlifting',
  'name': 'Deadlift Training',
  'category': 'Deadlift Training',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Conventional Deadlift',
                 'prescription': '5 x 5 at 80% 1RM',
                 'notes': 'Rest 3–4 minutes between sets.'},
                {'name': 'Sumo Deadlift', 'prescription': '5 x 5', 'notes': 'Focus on leg drive and hip positioning.'},
                {'name': 'Romanian Deadlift',
                 'prescription': '4 x 10',
                 'notes': 'Lower to just below knees before standing.'},
                {'name': 'Deficit Deadlift',
                 'prescription': '4 x 5',
                 'notes': 'Stand on a 5 cm platform and emphasize pull from floor.'},
                {'name': 'Rack Pull',
                 'prescription': '5 x 5',
                 'notes': 'Set safety pins just below knees and use heavy weight.'},
                {'name': 'Stiff-Leg Deadlift', 'prescription': '4 x 8', 'notes': 'Maintain nearly straight knees.'},
                {'name': 'Snatch-Grip Deadlift', 'prescription': '4 x 6', 'notes': 'Use a wide snatch grip.'},
                {'name': 'Tempo Deadlift', 'prescription': '4 x 5', 'notes': 'Lower over 5 seconds.'},
                {'name': 'Paused Deadlift', 'prescription': '5 x 4', 'notes': 'Pause 2 seconds just below knees.'},
                {'name': 'Deadlift Lockout Focus',
                 'prescription': '5 x 3 at 85–90% 1RM',
                 'notes': 'Emphasize strong lockout.'},
                {'name': 'Deadlift Volume Challenge',
                 'prescription': '50 conventional deadlifts at 60% 1RM',
                 'notes': 'Use as few sets as possible.'},
                {'name': 'Complete Deadlift Circuit',
                 'prescription': '4 rounds',
                 'notes': '5 conventional deadlifts, 5 Romanian deadlifts, 5 deficit deadlifts, 5 rack pulls.'}],
  'level': 'intermediate',
  'focus': 'deadlift training'},
 {'sport': 'weightlifting',
  'name': 'Bench Press Training',
  'category': 'Bench Press Training',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Heavy Flat Bench Press',
                 'prescription': '5 x 5 at 80% 1RM',
                 'notes': 'Rest 3–4 minutes between sets.'},
                {'name': 'Paused Bench Press',
                 'prescription': '5 x 4',
                 'notes': 'Pause on chest for 2 seconds before pressing explosively.'},
                {'name': 'Close-Grip Bench Press',
                 'prescription': '4 x 8',
                 'notes': 'Hands shoulder-width to emphasize triceps.'},
                {'name': 'Incline Bench Press',
                 'prescription': '4 x 8',
                 'notes': 'Use 30–45° incline and controlled descent.'},
                {'name': 'Spoto Press', 'prescription': '5 x 5', 'notes': 'Pause 2–3 cm above chest for 2 seconds.'},
                {'name': 'Larsen Press',
                 'prescription': '4 x 8',
                 'notes': 'Feet elevated; rely on upper-body stability.'},
                {'name': 'Floor Press', 'prescription': '5 x 6', 'notes': 'Pause when elbows touch ground.'},
                {'name': 'Speed Bench Press', 'prescription': '8 x 3 at 50–60% 1RM', 'notes': 'Press explosively.'},
                {'name': 'Bench Press Lockout',
                 'prescription': '5 x 4',
                 'notes': 'Start from pins 10–15 cm above chest.'},
                {'name': 'Bench Press Endurance',
                 'prescription': '60 reps at 55% 1RM',
                 'notes': 'Use as few sets as possible.'},
                {'name': 'Bench Press Pyramid', 'prescription': '10@50%, 8@60%, 6@70%, 4@80%, 2@90%, then descend'},
                {'name': 'Complete Bench Circuit',
                 'prescription': '4 rounds',
                 'notes': '5 flat bench, 5 incline bench, 5 close-grip bench, 5 paused bench.'}],
  'level': 'intermediate',
  'focus': 'bench press training'},
 {'sport': 'weightlifting',
  'name': 'Overhead Press Training',
  'category': 'Overhead Press Training',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Strict Overhead Press',
                 'prescription': '5 x 5 at 75–80% 1RM',
                 'notes': 'Keep legs completely still.'},
                {'name': 'Push Press', 'prescription': '5 x 5', 'notes': 'Controlled dip and explosive leg drive.'},
                {'name': 'Split Jerk', 'prescription': '5 x 3', 'notes': 'Focus on foot placement and stable lockout.'},
                {'name': 'Push Jerk', 'prescription': '5 x 4', 'notes': 'Drive overhead then drop underneath.'},
                {'name': 'Behind-the-Neck Press', 'prescription': '4 x 8', 'notes': 'Maintain shoulder control.'},
                {'name': 'Seated Overhead Press', 'prescription': '4 x 10', 'notes': 'Eliminate leg assistance.'},
                {'name': 'Pin Press', 'prescription': '5 x 4', 'notes': 'Start on safety pins at forehead height.'},
                {'name': 'Overhead Hold',
                 'prescription': '5 x 30 seconds',
                 'notes': 'Hold locked-out overhead position.'},
                {'name': 'Tempo Strict Press', 'prescription': '4 x 6', 'notes': 'Lower over 4 seconds.'},
                {'name': 'Push Press Speed Work', 'prescription': '8 x 3 at 60% 1RM', 'notes': 'Maximize bar speed.'},
                {'name': 'Press Endurance Challenge',
                 'prescription': '50 strict presses at 50% 1RM',
                 'notes': 'Use as few sets as possible.'},
                {'name': 'Complete Overhead Circuit',
                 'prescription': '4 rounds',
                 'notes': '5 strict presses, 5 push presses, 5 push jerks, 30-second overhead hold.'}],
  'level': 'intermediate',
  'focus': 'overhead press training'},
 {'sport': 'weightlifting',
  'name': 'Olympic Lift Training',
  'category': 'Olympic Lift Training',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Full Snatch',
                 'prescription': '6 x 2 at 70–80% 1RM',
                 'notes': 'Emphasize speed and receiving position.'},
                {'name': 'Full Clean & Jerk',
                 'prescription': '6 x 2 at 70–80% 1RM',
                 'notes': 'Focus on smooth transitions.'},
                {'name': 'Power Clean', 'prescription': '5 x 3', 'notes': 'Catch above parallel.'},
                {'name': 'Power Snatch', 'prescription': '5 x 3', 'notes': 'Receive above parallel with control.'},
                {'name': 'Hang Clean', 'prescription': '5 x 3', 'notes': 'Start above knees; emphasize hip extension.'},
                {'name': 'Hang Snatch', 'prescription': '5 x 3', 'notes': 'Maintain close bar path.'},
                {'name': 'Muscle Snatch', 'prescription': '4 x 5', 'notes': 'Press overhead without dropping under.'},
                {'name': 'Clean Pull + Clean', 'prescription': '5 sets', 'notes': '1 clean pull + 1 full clean.'},
                {'name': 'Snatch Pull + Snatch', 'prescription': '5 sets', 'notes': '1 snatch pull + 1 full snatch.'},
                {'name': 'Complex Lift Series',
                 'prescription': '6 sets',
                 'notes': '1 power clean, 1 front squat, 1 jerk.'},
                {'name': 'Olympic Lift EMOM',
                 'prescription': '12 minutes',
                 'notes': 'Every minute: 1 power clean + 1 push jerk.'},
                {'name': 'Competition Simulation',
                 'prescription': '3 snatch attempts + 3 clean & jerk attempts',
                 'notes': 'Use official competition standards and rest periods.'}],
  'level': 'intermediate',
  'focus': 'olympic lift training'},
 {'sport': 'weightlifting',
  'name': 'Pull Strength',
  'category': 'Pull Strength',
  'training_type': 'strength',
  'participants': 'alone',
  'exercises': [{'name': 'Pendlay Row', 'prescription': '5 x 6', 'notes': 'Start every rep from floor.'},
                {'name': 'Barbell Row', 'prescription': '4 x 8', 'notes': 'Torso approximately 45 degrees.'},
                {'name': 'Weighted Pull-Ups',
                 'prescription': '5 x 5',
                 'notes': 'Add weight if needed for near-maximal effort.'},
                {'name': 'Weighted Chin-Ups', 'prescription': '4 x 6', 'notes': 'Use a supinated grip.'},
                {'name': 'Clean Pull',
                 'prescription': '5 x 3 at 100–110% clean 1RM',
                 'notes': 'Fully extend hips and shrug.'},
                {'name': 'Snatch Pull', 'prescription': '5 x 3 at 100–110% snatch 1RM'},
                {'name': 'High Pull', 'prescription': '5 x 4', 'notes': 'Pull explosively to chest height.'},
                {'name': 'T-Bar Row', 'prescription': '4 x 10', 'notes': 'Squeeze shoulder blades at top.'},
                {'name': 'Deficit Barbell Row', 'prescription': '4 x 8', 'notes': 'Stand on 5 cm platform.'},
                {'name': 'Heavy Shrugs', 'prescription': '5 x 10', 'notes': 'Pause 1 second at top.'},
                {'name': 'Pull Strength Ladder',
                 'prescription': '5 rounds',
                 'notes': '5 Pendlay rows, 5 clean pulls, 5 weighted pull-ups.'},
                {'name': 'Complete Pull Circuit',
                 'prescription': '4 rounds',
                 'notes': '6 barbell rows, 6 clean pulls, 6 high pulls, 6 weighted chin-ups.'}],
  'level': 'intermediate',
  'focus': 'pull strength'},
 {'sport': 'weightlifting',
  'name': 'Explosive Power',
  'category': 'Explosive Power',
  'training_type': 'power',
  'participants': 'alone',
  'exercises': [{'name': 'Jump Squats',
                 'prescription': '6 x 5 at 20–30% back squat 1RM',
                 'notes': 'Jump as high as possible.'},
                {'name': 'Hang Power Clean', 'prescription': '6 x 3 at 65–75% 1RM', 'notes': 'Maximize bar speed.'},
                {'name': 'Hang Power Snatch',
                 'prescription': '6 x 3',
                 'notes': 'Drive through hips and receive above parallel.'},
                {'name': 'High Pull Speed Work',
                 'prescription': '5 x 4 at 70% effort',
                 'notes': 'Pull explosively to upper chest.'},
                {'name': 'Speed Deadlift',
                 'prescription': '8 x 2 at 50–60% deadlift 1RM',
                 'notes': 'Accelerate the bar.'},
                {'name': 'Push Press Speed Repetitions',
                 'prescription': '6 x 4 at 60% push press 1RM',
                 'notes': 'Emphasize upward velocity.'},
                {'name': 'Broad Jump Series', 'prescription': '5 x 6', 'notes': 'Reset completely between jumps.'},
                {'name': 'Box Jump Progression', 'prescription': '5 x 8', 'notes': 'Step down after each jump.'},
                {'name': 'Medicine Ball Overhead Slams',
                 'prescription': '5 x 12',
                 'notes': 'Drive ball into ground forcefully.'},
                {'name': 'Clean Pull + Power Clean Complex',
                 'prescription': '6 sets',
                 'notes': '1 clean pull + 1 power clean; prioritize speed.'},
                {'name': 'Explosive Contrast Training',
                 'prescription': '5 rounds',
                 'notes': '3 back squats at 80% 1RM + 5 jump squats at 20% 1RM; rest 3 minutes.'},
                {'name': 'Complete Explosive Power Circuit',
                 'prescription': '5 rounds',
                 'notes': '3 hang power cleans, 5 jump squats, 5 box jumps, 3 push presses; rest 2–3 minutes.'}],
  'level': 'intermediate',
  'focus': 'explosive power'},
 {'sport': 'weightlifting',
  'name': 'Mobility & Technique',
  'category': 'Mobility & Technique',
  'training_type': 'mobility',
  'participants': 'alone',
  'exercises': [{'name': 'Ankle Mobility Routine',
                 'prescription': '3 rounds',
                 'notes': '15 knee-over-toe reps per leg, 30-second calf stretch per leg, 15 ankle circles each '
                          'direction.'},
                {'name': 'Hip Mobility Flow',
                 'prescription': '3 rounds',
                 'notes': '10 World’s Greatest Stretches per side, 15 Cossack squats, 15 hip airplanes per side.'},
                {'name': 'Thoracic Spine Mobility',
                 'prescription': '3 rounds',
                 'notes': '15 thoracic rotations per side, 15 foam roller extensions, 10 thread-the-needle per side.'},
                {'name': 'Shoulder Mobility Circuit',
                 'prescription': '3 rounds',
                 'notes': '20 PVC pass-throughs, 20 shoulder dislocates, 30-second overhead stretch.'},
                {'name': 'Front Rack Mobility',
                 'prescription': '5 rounds',
                 'notes': '45-second front rack hold + 15 front squat stretches.'},
                {'name': 'Overhead Squat Technique',
                 'prescription': '5 x 10',
                 'notes': 'Use PVC pipe or empty bar; emphasize balance and posture.'},
                {'name': 'Snatch Balance Technique',
                 'prescription': '5 x 5',
                 'notes': 'Use empty bar or light weight; focus on receiving speed.'},
                {'name': 'Bar Path Drill',
                 'prescription': '20 slow snatch pulls + 20 slow clean pulls',
                 'notes': 'Use empty bar and keep bar close.'},
                {'name': 'Tempo Front Squat', 'prescription': '4 x 6', 'notes': 'Lower over 5 seconds.'},
                {'name': 'Bracing Practice',
                 'prescription': '4 rounds',
                 'notes': '20 diaphragmatic brace reps x 8 seconds + 10 bodyweight squats while braced.'},
                {'name': 'Technique Complex',
                 'prescription': '4 rounds',
                 'notes': '5 overhead squats, 5 muscle snatches, 5 front squats, 5 strict presses with empty bar.'},
                {'name': 'Complete Mobility Circuit',
                 'prescription': '3 rounds',
                 'notes': '10 overhead squats, 10 PVC pass-throughs, 10 World’s Greatest Stretches each side, 10 front '
                          'rack stretches, 10 hip airplanes each side.'}],
  'level': 'intermediate',
  'focus': 'mobility & technique'},
 {'sport': 'weightlifting',
  'name': 'Competition Preparation',
  'category': 'Competition Preparation',
  'training_type': 'competition',
  'participants': 'alone',
  'exercises': [{'name': 'Heavy Singles Day',
                 'prescription': '5 warm-up sets + 5 singles at 90–95% 1RM',
                 'notes': 'Rest 4–5 minutes between heavy attempts.'},
                {'name': 'Mock Competition',
                 'prescription': '3 snatch attempts + 3 clean & jerk attempts',
                 'notes': 'Use official order and rest periods.'},
                {'name': 'Powerlifting Mock Meet',
                 'prescription': '3 squat attempts + 3 bench attempts + 3 deadlift attempts',
                 'notes': 'Follow official commands and timing.'},
                {'name': 'Attempt Selection Practice',
                 'prescription': 'Opener 90%, second 95%, third 98–102%',
                 'notes': 'Repeat for primary competition lift.'},
                {'name': 'Heavy Triple Progression',
                 'prescription': '5 x 3 at 85% 1RM',
                 'notes': 'Maintain competition-standard technique.'},
                {'name': 'Competition Commands Practice',
                 'prescription': '20 singles',
                 'notes': 'Follow official lifting commands depending on lift.'},
                {'name': 'Fatigue Competition Simulation',
                 'prescription': '10 rounds',
                 'notes': '5 burpees + 1 heavy lift at 85% 1RM.'},
                {'name': 'Time-Controlled Warm-Up', 'prescription': '20-minute warm-up + 3 heavy singles at 90% 1RM'},
                {'name': 'Opener Confidence Session',
                 'prescription': '8 singles at planned opener',
                 'notes': 'Rest 2–3 minutes.'},
                {'name': 'Peak Strength Session',
                 'prescription': '1 single at 92%, 1 at 95%, 1 at 97%',
                 'notes': 'Stop if bar speed or technique deteriorates.'},
                {'name': 'Meet Day Simulation',
                 'prescription': 'Full competition-day replication',
                 'notes': 'Dynamic warm-up, progressive sets, official sequence, rest periods, record all lifts.'},
                {'name': 'Complete Competition Circuit',
                 'prescription': '3 rounds at ~85% 1RM',
                 'notes': '1 heavy squat, 1 heavy bench press, 1 heavy deadlift, 1 heavy clean & jerk; rest 4–5 '
                          'minutes.'}],
  'level': 'intermediate',
  'focus': 'competition preparation'}]

TRAINING_CATALOG = WEIGHTLIFTING_SESSIONS
WORKOUTS = WEIGHTLIFTING_SESSIONS


def get_sessions() -> List[Dict[str, Any]]:
    return WEIGHTLIFTING_SESSIONS


def get_workouts() -> List[Dict[str, Any]]:
    return WEIGHTLIFTING_SESSIONS


def get_sessions_by_category(category: str) -> List[Dict[str, Any]]:
    category_key = category.lower().strip()
    return [s for s in WEIGHTLIFTING_SESSIONS if s.get("category", "").lower() == category_key]


def get_sessions_by_level(level: str) -> List[Dict[str, Any]]:
    level_key = level.lower().strip()
    return [s for s in WEIGHTLIFTING_SESSIONS if s.get("level", "").lower() == level_key]


def get_session_names() -> List[str]:
    return [s["name"] for s in WEIGHTLIFTING_SESSIONS]


if __name__ == "__main__":
    total_exercises = sum(len(s["exercises"]) for s in WEIGHTLIFTING_SESSIONS)
    print(f"{SPORT_NAME}: {len(WEIGHTLIFTING_SESSIONS)} sessions, {total_exercises} exercises")
